-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity stream is
generic (
    C_S_AXI_AXILITES_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_AXILITES_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    src_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    src_TVALID : IN STD_LOGIC;
    src_TREADY : OUT STD_LOGIC;
    src_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    src_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    dst_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    dst_TVALID : OUT STD_LOGIC;
    dst_TREADY : IN STD_LOGIC;
    dst_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    dst_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_AXILiteS_AWVALID : IN STD_LOGIC;
    s_axi_AXILiteS_AWREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_WVALID : IN STD_LOGIC;
    s_axi_AXILiteS_WREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH/8-1 downto 0);
    s_axi_AXILiteS_ARVALID : IN STD_LOGIC;
    s_axi_AXILiteS_ARREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_RVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_RREADY : IN STD_LOGIC;
    s_axi_AXILiteS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_AXILiteS_BVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_BREADY : IN STD_LOGIC;
    s_axi_AXILiteS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "stream,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.846000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=368,HLS_SYN_LUT=804,HLS_VERSION=2018_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv16_2B3 : STD_LOGIC_VECTOR (15 downto 0) := "0000001010110011";
    constant ap_const_lv32_FF000000 : STD_LOGIC_VECTOR (31 downto 0) := "11111111000000000000000000000000";
    constant ap_const_lv32_FFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "00000000111111111111111111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal src_V_data_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal src_V_data_V_0_vld_in : STD_LOGIC;
    signal src_V_data_V_0_vld_out : STD_LOGIC;
    signal src_V_data_V_0_ack_in : STD_LOGIC;
    signal src_V_data_V_0_ack_out : STD_LOGIC;
    signal src_V_data_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal src_V_data_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal src_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal src_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal src_V_data_V_0_sel : STD_LOGIC;
    signal src_V_data_V_0_load_A : STD_LOGIC;
    signal src_V_data_V_0_load_B : STD_LOGIC;
    signal src_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal src_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal src_V_keep_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal src_V_keep_V_0_vld_in : STD_LOGIC;
    signal src_V_keep_V_0_vld_out : STD_LOGIC;
    signal src_V_keep_V_0_ack_in : STD_LOGIC;
    signal src_V_keep_V_0_ack_out : STD_LOGIC;
    signal src_V_keep_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal src_V_keep_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal src_V_keep_V_0_sel_rd : STD_LOGIC := '0';
    signal src_V_keep_V_0_sel_wr : STD_LOGIC := '0';
    signal src_V_keep_V_0_sel : STD_LOGIC;
    signal src_V_keep_V_0_load_A : STD_LOGIC;
    signal src_V_keep_V_0_load_B : STD_LOGIC;
    signal src_V_keep_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal src_V_keep_V_0_state_cmp_full : STD_LOGIC;
    signal src_V_strb_V_0_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal src_V_strb_V_0_vld_in : STD_LOGIC;
    signal src_V_strb_V_0_vld_out : STD_LOGIC;
    signal src_V_strb_V_0_ack_in : STD_LOGIC;
    signal src_V_strb_V_0_ack_out : STD_LOGIC;
    signal src_V_strb_V_0_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal src_V_strb_V_0_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal src_V_strb_V_0_sel_rd : STD_LOGIC := '0';
    signal src_V_strb_V_0_sel_wr : STD_LOGIC := '0';
    signal src_V_strb_V_0_sel : STD_LOGIC;
    signal src_V_strb_V_0_load_A : STD_LOGIC;
    signal src_V_strb_V_0_load_B : STD_LOGIC;
    signal src_V_strb_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal src_V_strb_V_0_state_cmp_full : STD_LOGIC;
    signal src_V_user_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_user_V_0_vld_in : STD_LOGIC;
    signal src_V_user_V_0_vld_out : STD_LOGIC;
    signal src_V_user_V_0_ack_in : STD_LOGIC;
    signal src_V_user_V_0_ack_out : STD_LOGIC;
    signal src_V_user_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_user_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_user_V_0_sel_rd : STD_LOGIC := '0';
    signal src_V_user_V_0_sel_wr : STD_LOGIC := '0';
    signal src_V_user_V_0_sel : STD_LOGIC;
    signal src_V_user_V_0_load_A : STD_LOGIC;
    signal src_V_user_V_0_load_B : STD_LOGIC;
    signal src_V_user_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal src_V_user_V_0_state_cmp_full : STD_LOGIC;
    signal src_V_last_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_last_V_0_vld_in : STD_LOGIC;
    signal src_V_last_V_0_vld_out : STD_LOGIC;
    signal src_V_last_V_0_ack_in : STD_LOGIC;
    signal src_V_last_V_0_ack_out : STD_LOGIC;
    signal src_V_last_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_last_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_last_V_0_sel_rd : STD_LOGIC := '0';
    signal src_V_last_V_0_sel_wr : STD_LOGIC := '0';
    signal src_V_last_V_0_sel : STD_LOGIC;
    signal src_V_last_V_0_load_A : STD_LOGIC;
    signal src_V_last_V_0_load_B : STD_LOGIC;
    signal src_V_last_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal src_V_last_V_0_state_cmp_full : STD_LOGIC;
    signal src_V_id_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_id_V_0_vld_in : STD_LOGIC;
    signal src_V_id_V_0_vld_out : STD_LOGIC;
    signal src_V_id_V_0_ack_in : STD_LOGIC;
    signal src_V_id_V_0_ack_out : STD_LOGIC;
    signal src_V_id_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_id_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_id_V_0_sel_rd : STD_LOGIC := '0';
    signal src_V_id_V_0_sel_wr : STD_LOGIC := '0';
    signal src_V_id_V_0_sel : STD_LOGIC;
    signal src_V_id_V_0_load_A : STD_LOGIC;
    signal src_V_id_V_0_load_B : STD_LOGIC;
    signal src_V_id_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal src_V_id_V_0_state_cmp_full : STD_LOGIC;
    signal src_V_dest_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_dest_V_0_vld_in : STD_LOGIC;
    signal src_V_dest_V_0_vld_out : STD_LOGIC;
    signal src_V_dest_V_0_ack_in : STD_LOGIC;
    signal src_V_dest_V_0_ack_out : STD_LOGIC;
    signal src_V_dest_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_dest_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal src_V_dest_V_0_sel_rd : STD_LOGIC := '0';
    signal src_V_dest_V_0_sel_wr : STD_LOGIC := '0';
    signal src_V_dest_V_0_sel : STD_LOGIC;
    signal src_V_dest_V_0_load_A : STD_LOGIC;
    signal src_V_dest_V_0_load_B : STD_LOGIC;
    signal src_V_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal src_V_dest_V_0_state_cmp_full : STD_LOGIC;
    signal dst_V_data_V_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_V_data_V_1_vld_in : STD_LOGIC;
    signal dst_V_data_V_1_vld_out : STD_LOGIC;
    signal dst_V_data_V_1_ack_in : STD_LOGIC;
    signal dst_V_data_V_1_ack_out : STD_LOGIC;
    signal dst_V_data_V_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_V_data_V_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal dst_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal dst_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal dst_V_data_V_1_sel : STD_LOGIC;
    signal dst_V_data_V_1_load_A : STD_LOGIC;
    signal dst_V_data_V_1_load_B : STD_LOGIC;
    signal dst_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dst_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal dst_V_keep_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal dst_V_keep_V_1_vld_in : STD_LOGIC;
    signal dst_V_keep_V_1_vld_out : STD_LOGIC;
    signal dst_V_keep_V_1_ack_in : STD_LOGIC;
    signal dst_V_keep_V_1_ack_out : STD_LOGIC;
    signal dst_V_keep_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal dst_V_keep_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal dst_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal dst_V_keep_V_1_sel_wr : STD_LOGIC := '0';
    signal dst_V_keep_V_1_sel : STD_LOGIC;
    signal dst_V_keep_V_1_load_A : STD_LOGIC;
    signal dst_V_keep_V_1_load_B : STD_LOGIC;
    signal dst_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dst_V_keep_V_1_state_cmp_full : STD_LOGIC;
    signal dst_V_strb_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal dst_V_strb_V_1_vld_in : STD_LOGIC;
    signal dst_V_strb_V_1_vld_out : STD_LOGIC;
    signal dst_V_strb_V_1_ack_in : STD_LOGIC;
    signal dst_V_strb_V_1_ack_out : STD_LOGIC;
    signal dst_V_strb_V_1_payload_A : STD_LOGIC_VECTOR (3 downto 0);
    signal dst_V_strb_V_1_payload_B : STD_LOGIC_VECTOR (3 downto 0);
    signal dst_V_strb_V_1_sel_rd : STD_LOGIC := '0';
    signal dst_V_strb_V_1_sel_wr : STD_LOGIC := '0';
    signal dst_V_strb_V_1_sel : STD_LOGIC;
    signal dst_V_strb_V_1_load_A : STD_LOGIC;
    signal dst_V_strb_V_1_load_B : STD_LOGIC;
    signal dst_V_strb_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dst_V_strb_V_1_state_cmp_full : STD_LOGIC;
    signal dst_V_user_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_user_V_1_vld_in : STD_LOGIC;
    signal dst_V_user_V_1_vld_out : STD_LOGIC;
    signal dst_V_user_V_1_ack_in : STD_LOGIC;
    signal dst_V_user_V_1_ack_out : STD_LOGIC;
    signal dst_V_user_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_user_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_user_V_1_sel_rd : STD_LOGIC := '0';
    signal dst_V_user_V_1_sel_wr : STD_LOGIC := '0';
    signal dst_V_user_V_1_sel : STD_LOGIC;
    signal dst_V_user_V_1_load_A : STD_LOGIC;
    signal dst_V_user_V_1_load_B : STD_LOGIC;
    signal dst_V_user_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dst_V_user_V_1_state_cmp_full : STD_LOGIC;
    signal dst_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_last_V_1_vld_in : STD_LOGIC;
    signal dst_V_last_V_1_vld_out : STD_LOGIC;
    signal dst_V_last_V_1_ack_in : STD_LOGIC;
    signal dst_V_last_V_1_ack_out : STD_LOGIC;
    signal dst_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal dst_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal dst_V_last_V_1_sel : STD_LOGIC;
    signal dst_V_last_V_1_load_A : STD_LOGIC;
    signal dst_V_last_V_1_load_B : STD_LOGIC;
    signal dst_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dst_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal dst_V_id_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_id_V_1_vld_in : STD_LOGIC;
    signal dst_V_id_V_1_vld_out : STD_LOGIC;
    signal dst_V_id_V_1_ack_in : STD_LOGIC;
    signal dst_V_id_V_1_ack_out : STD_LOGIC;
    signal dst_V_id_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_id_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_id_V_1_sel_rd : STD_LOGIC := '0';
    signal dst_V_id_V_1_sel_wr : STD_LOGIC := '0';
    signal dst_V_id_V_1_sel : STD_LOGIC;
    signal dst_V_id_V_1_load_A : STD_LOGIC;
    signal dst_V_id_V_1_load_B : STD_LOGIC;
    signal dst_V_id_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dst_V_id_V_1_state_cmp_full : STD_LOGIC;
    signal dst_V_dest_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_dest_V_1_vld_in : STD_LOGIC;
    signal dst_V_dest_V_1_vld_out : STD_LOGIC;
    signal dst_V_dest_V_1_ack_in : STD_LOGIC;
    signal dst_V_dest_V_1_ack_out : STD_LOGIC;
    signal dst_V_dest_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_dest_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal dst_V_dest_V_1_sel_rd : STD_LOGIC := '0';
    signal dst_V_dest_V_1_sel_wr : STD_LOGIC := '0';
    signal dst_V_dest_V_1_sel : STD_LOGIC;
    signal dst_V_dest_V_1_load_A : STD_LOGIC;
    signal dst_V_dest_V_1_load_B : STD_LOGIC;
    signal dst_V_dest_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal dst_V_dest_V_1_state_cmp_full : STD_LOGIC;
    signal mask : STD_LOGIC_VECTOR (31 downto 0);
    signal x : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal src_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal dst_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal mask_read_reg_239 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_last_V_fu_144_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_259 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_fu_196_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_5_fu_205_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_227_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_fu_159_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not1_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal invert_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_fu_184_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal brmerge_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_fu_190_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_924 : BOOLEAN;

    component stream_AXILiteS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        mask : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    stream_AXILiteS_s_axi_U : component stream_AXILiteS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXILITES_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXILITES_DATA_WIDTH)
    port map (
        AWVALID => s_axi_AXILiteS_AWVALID,
        AWREADY => s_axi_AXILiteS_AWREADY,
        AWADDR => s_axi_AXILiteS_AWADDR,
        WVALID => s_axi_AXILiteS_WVALID,
        WREADY => s_axi_AXILiteS_WREADY,
        WDATA => s_axi_AXILiteS_WDATA,
        WSTRB => s_axi_AXILiteS_WSTRB,
        ARVALID => s_axi_AXILiteS_ARVALID,
        ARREADY => s_axi_AXILiteS_ARREADY,
        ARADDR => s_axi_AXILiteS_ARADDR,
        RVALID => s_axi_AXILiteS_RVALID,
        RREADY => s_axi_AXILiteS_RREADY,
        RDATA => s_axi_AXILiteS_RDATA,
        RRESP => s_axi_AXILiteS_RRESP,
        BVALID => s_axi_AXILiteS_BVALID,
        BREADY => s_axi_AXILiteS_BREADY,
        BRESP => s_axi_AXILiteS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        mask => mask);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    dst_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((dst_V_data_V_1_ack_out = ap_const_logic_1) and (dst_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        dst_V_data_V_1_sel_rd <= not(dst_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dst_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((dst_V_data_V_1_ack_in = ap_const_logic_1) and (dst_V_data_V_1_vld_in = ap_const_logic_1))) then 
                                        dst_V_data_V_1_sel_wr <= not(dst_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    dst_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((dst_V_data_V_1_state = ap_const_lv2_2) and (dst_V_data_V_1_vld_in = ap_const_logic_0)) or ((dst_V_data_V_1_state = ap_const_lv2_3) and (dst_V_data_V_1_vld_in = ap_const_logic_0) and (dst_V_data_V_1_ack_out = ap_const_logic_1)))) then 
                    dst_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((dst_V_data_V_1_state = ap_const_lv2_1) and (dst_V_data_V_1_ack_out = ap_const_logic_0)) or ((dst_V_data_V_1_state = ap_const_lv2_3) and (dst_V_data_V_1_ack_out = ap_const_logic_0) and (dst_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((dst_V_data_V_1_vld_in = ap_const_logic_0) and (dst_V_data_V_1_ack_out = ap_const_logic_1))) and not(((dst_V_data_V_1_ack_out = ap_const_logic_0) and (dst_V_data_V_1_vld_in = ap_const_logic_1))) and (dst_V_data_V_1_state = ap_const_lv2_3)) or ((dst_V_data_V_1_state = ap_const_lv2_1) and (dst_V_data_V_1_ack_out = ap_const_logic_1)) or ((dst_V_data_V_1_state = ap_const_lv2_2) and (dst_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    dst_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    dst_V_dest_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_dest_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((dst_V_dest_V_1_ack_out = ap_const_logic_1) and (dst_V_dest_V_1_vld_out = ap_const_logic_1))) then 
                                        dst_V_dest_V_1_sel_rd <= not(dst_V_dest_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dst_V_dest_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_dest_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((dst_V_dest_V_1_ack_in = ap_const_logic_1) and (dst_V_dest_V_1_vld_in = ap_const_logic_1))) then 
                                        dst_V_dest_V_1_sel_wr <= not(dst_V_dest_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    dst_V_dest_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_dest_V_1_state <= ap_const_lv2_0;
            else
                if ((((dst_V_dest_V_1_state = ap_const_lv2_2) and (dst_V_dest_V_1_vld_in = ap_const_logic_0)) or ((dst_V_dest_V_1_state = ap_const_lv2_3) and (dst_V_dest_V_1_vld_in = ap_const_logic_0) and (dst_V_dest_V_1_ack_out = ap_const_logic_1)))) then 
                    dst_V_dest_V_1_state <= ap_const_lv2_2;
                elsif ((((dst_V_dest_V_1_state = ap_const_lv2_1) and (dst_V_dest_V_1_ack_out = ap_const_logic_0)) or ((dst_V_dest_V_1_state = ap_const_lv2_3) and (dst_V_dest_V_1_ack_out = ap_const_logic_0) and (dst_V_dest_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_dest_V_1_state <= ap_const_lv2_1;
                elsif (((not(((dst_V_dest_V_1_vld_in = ap_const_logic_0) and (dst_V_dest_V_1_ack_out = ap_const_logic_1))) and not(((dst_V_dest_V_1_ack_out = ap_const_logic_0) and (dst_V_dest_V_1_vld_in = ap_const_logic_1))) and (dst_V_dest_V_1_state = ap_const_lv2_3)) or ((dst_V_dest_V_1_state = ap_const_lv2_1) and (dst_V_dest_V_1_ack_out = ap_const_logic_1)) or ((dst_V_dest_V_1_state = ap_const_lv2_2) and (dst_V_dest_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_dest_V_1_state <= ap_const_lv2_3;
                else 
                    dst_V_dest_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    dst_V_id_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_id_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((dst_V_id_V_1_ack_out = ap_const_logic_1) and (dst_V_id_V_1_vld_out = ap_const_logic_1))) then 
                                        dst_V_id_V_1_sel_rd <= not(dst_V_id_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dst_V_id_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_id_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((dst_V_id_V_1_ack_in = ap_const_logic_1) and (dst_V_id_V_1_vld_in = ap_const_logic_1))) then 
                                        dst_V_id_V_1_sel_wr <= not(dst_V_id_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    dst_V_id_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_id_V_1_state <= ap_const_lv2_0;
            else
                if ((((dst_V_id_V_1_state = ap_const_lv2_2) and (dst_V_id_V_1_vld_in = ap_const_logic_0)) or ((dst_V_id_V_1_state = ap_const_lv2_3) and (dst_V_id_V_1_vld_in = ap_const_logic_0) and (dst_V_id_V_1_ack_out = ap_const_logic_1)))) then 
                    dst_V_id_V_1_state <= ap_const_lv2_2;
                elsif ((((dst_V_id_V_1_state = ap_const_lv2_1) and (dst_V_id_V_1_ack_out = ap_const_logic_0)) or ((dst_V_id_V_1_state = ap_const_lv2_3) and (dst_V_id_V_1_ack_out = ap_const_logic_0) and (dst_V_id_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_id_V_1_state <= ap_const_lv2_1;
                elsif (((not(((dst_V_id_V_1_vld_in = ap_const_logic_0) and (dst_V_id_V_1_ack_out = ap_const_logic_1))) and not(((dst_V_id_V_1_ack_out = ap_const_logic_0) and (dst_V_id_V_1_vld_in = ap_const_logic_1))) and (dst_V_id_V_1_state = ap_const_lv2_3)) or ((dst_V_id_V_1_state = ap_const_lv2_1) and (dst_V_id_V_1_ack_out = ap_const_logic_1)) or ((dst_V_id_V_1_state = ap_const_lv2_2) and (dst_V_id_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_id_V_1_state <= ap_const_lv2_3;
                else 
                    dst_V_id_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    dst_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((dst_V_keep_V_1_ack_out = ap_const_logic_1) and (dst_V_keep_V_1_vld_out = ap_const_logic_1))) then 
                                        dst_V_keep_V_1_sel_rd <= not(dst_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dst_V_keep_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_keep_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((dst_V_keep_V_1_ack_in = ap_const_logic_1) and (dst_V_keep_V_1_vld_in = ap_const_logic_1))) then 
                                        dst_V_keep_V_1_sel_wr <= not(dst_V_keep_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    dst_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((dst_V_keep_V_1_state = ap_const_lv2_2) and (dst_V_keep_V_1_vld_in = ap_const_logic_0)) or ((dst_V_keep_V_1_state = ap_const_lv2_3) and (dst_V_keep_V_1_vld_in = ap_const_logic_0) and (dst_V_keep_V_1_ack_out = ap_const_logic_1)))) then 
                    dst_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((dst_V_keep_V_1_state = ap_const_lv2_1) and (dst_V_keep_V_1_ack_out = ap_const_logic_0)) or ((dst_V_keep_V_1_state = ap_const_lv2_3) and (dst_V_keep_V_1_ack_out = ap_const_logic_0) and (dst_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_keep_V_1_state <= ap_const_lv2_1;
                elsif (((not(((dst_V_keep_V_1_vld_in = ap_const_logic_0) and (dst_V_keep_V_1_ack_out = ap_const_logic_1))) and not(((dst_V_keep_V_1_ack_out = ap_const_logic_0) and (dst_V_keep_V_1_vld_in = ap_const_logic_1))) and (dst_V_keep_V_1_state = ap_const_lv2_3)) or ((dst_V_keep_V_1_state = ap_const_lv2_1) and (dst_V_keep_V_1_ack_out = ap_const_logic_1)) or ((dst_V_keep_V_1_state = ap_const_lv2_2) and (dst_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    dst_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    dst_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((dst_V_last_V_1_ack_out = ap_const_logic_1) and (dst_V_last_V_1_vld_out = ap_const_logic_1))) then 
                                        dst_V_last_V_1_sel_rd <= not(dst_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dst_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((dst_V_last_V_1_ack_in = ap_const_logic_1) and (dst_V_last_V_1_vld_in = ap_const_logic_1))) then 
                                        dst_V_last_V_1_sel_wr <= not(dst_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    dst_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((dst_V_last_V_1_state = ap_const_lv2_2) and (dst_V_last_V_1_vld_in = ap_const_logic_0)) or ((dst_V_last_V_1_state = ap_const_lv2_3) and (dst_V_last_V_1_vld_in = ap_const_logic_0) and (dst_V_last_V_1_ack_out = ap_const_logic_1)))) then 
                    dst_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((dst_V_last_V_1_state = ap_const_lv2_1) and (dst_V_last_V_1_ack_out = ap_const_logic_0)) or ((dst_V_last_V_1_state = ap_const_lv2_3) and (dst_V_last_V_1_ack_out = ap_const_logic_0) and (dst_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_last_V_1_state <= ap_const_lv2_1;
                elsif (((not(((dst_V_last_V_1_vld_in = ap_const_logic_0) and (dst_V_last_V_1_ack_out = ap_const_logic_1))) and not(((dst_V_last_V_1_ack_out = ap_const_logic_0) and (dst_V_last_V_1_vld_in = ap_const_logic_1))) and (dst_V_last_V_1_state = ap_const_lv2_3)) or ((dst_V_last_V_1_state = ap_const_lv2_1) and (dst_V_last_V_1_ack_out = ap_const_logic_1)) or ((dst_V_last_V_1_state = ap_const_lv2_2) and (dst_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    dst_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    dst_V_strb_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_strb_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((dst_V_strb_V_1_ack_out = ap_const_logic_1) and (dst_V_strb_V_1_vld_out = ap_const_logic_1))) then 
                                        dst_V_strb_V_1_sel_rd <= not(dst_V_strb_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dst_V_strb_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_strb_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((dst_V_strb_V_1_ack_in = ap_const_logic_1) and (dst_V_strb_V_1_vld_in = ap_const_logic_1))) then 
                                        dst_V_strb_V_1_sel_wr <= not(dst_V_strb_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    dst_V_strb_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_strb_V_1_state <= ap_const_lv2_0;
            else
                if ((((dst_V_strb_V_1_state = ap_const_lv2_2) and (dst_V_strb_V_1_vld_in = ap_const_logic_0)) or ((dst_V_strb_V_1_state = ap_const_lv2_3) and (dst_V_strb_V_1_vld_in = ap_const_logic_0) and (dst_V_strb_V_1_ack_out = ap_const_logic_1)))) then 
                    dst_V_strb_V_1_state <= ap_const_lv2_2;
                elsif ((((dst_V_strb_V_1_state = ap_const_lv2_1) and (dst_V_strb_V_1_ack_out = ap_const_logic_0)) or ((dst_V_strb_V_1_state = ap_const_lv2_3) and (dst_V_strb_V_1_ack_out = ap_const_logic_0) and (dst_V_strb_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_strb_V_1_state <= ap_const_lv2_1;
                elsif (((not(((dst_V_strb_V_1_vld_in = ap_const_logic_0) and (dst_V_strb_V_1_ack_out = ap_const_logic_1))) and not(((dst_V_strb_V_1_ack_out = ap_const_logic_0) and (dst_V_strb_V_1_vld_in = ap_const_logic_1))) and (dst_V_strb_V_1_state = ap_const_lv2_3)) or ((dst_V_strb_V_1_state = ap_const_lv2_1) and (dst_V_strb_V_1_ack_out = ap_const_logic_1)) or ((dst_V_strb_V_1_state = ap_const_lv2_2) and (dst_V_strb_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_strb_V_1_state <= ap_const_lv2_3;
                else 
                    dst_V_strb_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    dst_V_user_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_user_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((dst_V_user_V_1_ack_out = ap_const_logic_1) and (dst_V_user_V_1_vld_out = ap_const_logic_1))) then 
                                        dst_V_user_V_1_sel_rd <= not(dst_V_user_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    dst_V_user_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_user_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((dst_V_user_V_1_ack_in = ap_const_logic_1) and (dst_V_user_V_1_vld_in = ap_const_logic_1))) then 
                                        dst_V_user_V_1_sel_wr <= not(dst_V_user_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    dst_V_user_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                dst_V_user_V_1_state <= ap_const_lv2_0;
            else
                if ((((dst_V_user_V_1_state = ap_const_lv2_2) and (dst_V_user_V_1_vld_in = ap_const_logic_0)) or ((dst_V_user_V_1_state = ap_const_lv2_3) and (dst_V_user_V_1_vld_in = ap_const_logic_0) and (dst_V_user_V_1_ack_out = ap_const_logic_1)))) then 
                    dst_V_user_V_1_state <= ap_const_lv2_2;
                elsif ((((dst_V_user_V_1_state = ap_const_lv2_1) and (dst_V_user_V_1_ack_out = ap_const_logic_0)) or ((dst_V_user_V_1_state = ap_const_lv2_3) and (dst_V_user_V_1_ack_out = ap_const_logic_0) and (dst_V_user_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_user_V_1_state <= ap_const_lv2_1;
                elsif (((not(((dst_V_user_V_1_vld_in = ap_const_logic_0) and (dst_V_user_V_1_ack_out = ap_const_logic_1))) and not(((dst_V_user_V_1_ack_out = ap_const_logic_0) and (dst_V_user_V_1_vld_in = ap_const_logic_1))) and (dst_V_user_V_1_state = ap_const_lv2_3)) or ((dst_V_user_V_1_state = ap_const_lv2_1) and (dst_V_user_V_1_ack_out = ap_const_logic_1)) or ((dst_V_user_V_1_state = ap_const_lv2_2) and (dst_V_user_V_1_vld_in = ap_const_logic_1)))) then 
                    dst_V_user_V_1_state <= ap_const_lv2_3;
                else 
                    dst_V_user_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    src_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((src_V_data_V_0_ack_out = ap_const_logic_1) and (src_V_data_V_0_vld_out = ap_const_logic_1))) then 
                                        src_V_data_V_0_sel_rd <= not(src_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    src_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((src_V_data_V_0_ack_in = ap_const_logic_1) and (src_V_data_V_0_vld_in = ap_const_logic_1))) then 
                                        src_V_data_V_0_sel_wr <= not(src_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    src_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((src_V_data_V_0_vld_in = ap_const_logic_0) and (src_V_data_V_0_state = ap_const_lv2_2)) or ((src_V_data_V_0_vld_in = ap_const_logic_0) and (src_V_data_V_0_state = ap_const_lv2_3) and (src_V_data_V_0_ack_out = ap_const_logic_1)))) then 
                    src_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((src_V_data_V_0_ack_out = ap_const_logic_0) and (src_V_data_V_0_state = ap_const_lv2_1)) or ((src_V_data_V_0_ack_out = ap_const_logic_0) and (src_V_data_V_0_state = ap_const_lv2_3) and (src_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((src_V_data_V_0_vld_in = ap_const_logic_0) and (src_V_data_V_0_ack_out = ap_const_logic_1))) and not(((src_V_data_V_0_ack_out = ap_const_logic_0) and (src_V_data_V_0_vld_in = ap_const_logic_1))) and (src_V_data_V_0_state = ap_const_lv2_3)) or ((src_V_data_V_0_state = ap_const_lv2_1) and (src_V_data_V_0_ack_out = ap_const_logic_1)) or ((src_V_data_V_0_state = ap_const_lv2_2) and (src_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    src_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    src_V_dest_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_dest_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((src_V_dest_V_0_ack_out = ap_const_logic_1) and (src_V_dest_V_0_vld_out = ap_const_logic_1))) then 
                                        src_V_dest_V_0_sel_rd <= not(src_V_dest_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    src_V_dest_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_dest_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((src_V_dest_V_0_ack_in = ap_const_logic_1) and (src_V_dest_V_0_vld_in = ap_const_logic_1))) then 
                                        src_V_dest_V_0_sel_wr <= not(src_V_dest_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    src_V_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((src_V_dest_V_0_state = ap_const_lv2_2) and (src_V_dest_V_0_vld_in = ap_const_logic_0)) or ((src_V_dest_V_0_state = ap_const_lv2_3) and (src_V_dest_V_0_vld_in = ap_const_logic_0) and (src_V_dest_V_0_ack_out = ap_const_logic_1)))) then 
                    src_V_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((src_V_dest_V_0_state = ap_const_lv2_1) and (src_V_dest_V_0_ack_out = ap_const_logic_0)) or ((src_V_dest_V_0_state = ap_const_lv2_3) and (src_V_dest_V_0_ack_out = ap_const_logic_0) and (src_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((src_V_dest_V_0_vld_in = ap_const_logic_0) and (src_V_dest_V_0_ack_out = ap_const_logic_1))) and not(((src_V_dest_V_0_ack_out = ap_const_logic_0) and (src_V_dest_V_0_vld_in = ap_const_logic_1))) and (src_V_dest_V_0_state = ap_const_lv2_3)) or ((src_V_dest_V_0_state = ap_const_lv2_1) and (src_V_dest_V_0_ack_out = ap_const_logic_1)) or ((src_V_dest_V_0_state = ap_const_lv2_2) and (src_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_dest_V_0_state <= ap_const_lv2_3;
                else 
                    src_V_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    src_V_id_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_id_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((src_V_id_V_0_ack_out = ap_const_logic_1) and (src_V_id_V_0_vld_out = ap_const_logic_1))) then 
                                        src_V_id_V_0_sel_rd <= not(src_V_id_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    src_V_id_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_id_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((src_V_id_V_0_ack_in = ap_const_logic_1) and (src_V_id_V_0_vld_in = ap_const_logic_1))) then 
                                        src_V_id_V_0_sel_wr <= not(src_V_id_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    src_V_id_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_id_V_0_state <= ap_const_lv2_0;
            else
                if ((((src_V_id_V_0_state = ap_const_lv2_2) and (src_V_id_V_0_vld_in = ap_const_logic_0)) or ((src_V_id_V_0_state = ap_const_lv2_3) and (src_V_id_V_0_vld_in = ap_const_logic_0) and (src_V_id_V_0_ack_out = ap_const_logic_1)))) then 
                    src_V_id_V_0_state <= ap_const_lv2_2;
                elsif ((((src_V_id_V_0_state = ap_const_lv2_1) and (src_V_id_V_0_ack_out = ap_const_logic_0)) or ((src_V_id_V_0_state = ap_const_lv2_3) and (src_V_id_V_0_ack_out = ap_const_logic_0) and (src_V_id_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_id_V_0_state <= ap_const_lv2_1;
                elsif (((not(((src_V_id_V_0_vld_in = ap_const_logic_0) and (src_V_id_V_0_ack_out = ap_const_logic_1))) and not(((src_V_id_V_0_ack_out = ap_const_logic_0) and (src_V_id_V_0_vld_in = ap_const_logic_1))) and (src_V_id_V_0_state = ap_const_lv2_3)) or ((src_V_id_V_0_state = ap_const_lv2_1) and (src_V_id_V_0_ack_out = ap_const_logic_1)) or ((src_V_id_V_0_state = ap_const_lv2_2) and (src_V_id_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_id_V_0_state <= ap_const_lv2_3;
                else 
                    src_V_id_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    src_V_keep_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_keep_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((src_V_keep_V_0_ack_out = ap_const_logic_1) and (src_V_keep_V_0_vld_out = ap_const_logic_1))) then 
                                        src_V_keep_V_0_sel_rd <= not(src_V_keep_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    src_V_keep_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_keep_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((src_V_keep_V_0_ack_in = ap_const_logic_1) and (src_V_keep_V_0_vld_in = ap_const_logic_1))) then 
                                        src_V_keep_V_0_sel_wr <= not(src_V_keep_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    src_V_keep_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_keep_V_0_state <= ap_const_lv2_0;
            else
                if ((((src_V_keep_V_0_state = ap_const_lv2_3) and (src_V_keep_V_0_vld_in = ap_const_logic_0) and (src_V_keep_V_0_ack_out = ap_const_logic_1)) or ((src_V_keep_V_0_state = ap_const_lv2_2) and (src_V_keep_V_0_vld_in = ap_const_logic_0)))) then 
                    src_V_keep_V_0_state <= ap_const_lv2_2;
                elsif ((((src_V_keep_V_0_state = ap_const_lv2_1) and (src_V_keep_V_0_ack_out = ap_const_logic_0)) or ((src_V_keep_V_0_state = ap_const_lv2_3) and (src_V_keep_V_0_ack_out = ap_const_logic_0) and (src_V_keep_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_keep_V_0_state <= ap_const_lv2_1;
                elsif ((((src_V_keep_V_0_state = ap_const_lv2_1) and (src_V_keep_V_0_ack_out = ap_const_logic_1)) or ((src_V_keep_V_0_state = ap_const_lv2_2) and (src_V_keep_V_0_vld_in = ap_const_logic_1)) or (not(((src_V_keep_V_0_vld_in = ap_const_logic_0) and (src_V_keep_V_0_ack_out = ap_const_logic_1))) and not(((src_V_keep_V_0_ack_out = ap_const_logic_0) and (src_V_keep_V_0_vld_in = ap_const_logic_1))) and (src_V_keep_V_0_state = ap_const_lv2_3)))) then 
                    src_V_keep_V_0_state <= ap_const_lv2_3;
                else 
                    src_V_keep_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    src_V_last_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_last_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((src_V_last_V_0_ack_out = ap_const_logic_1) and (src_V_last_V_0_vld_out = ap_const_logic_1))) then 
                                        src_V_last_V_0_sel_rd <= not(src_V_last_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    src_V_last_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_last_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((src_V_last_V_0_ack_in = ap_const_logic_1) and (src_V_last_V_0_vld_in = ap_const_logic_1))) then 
                                        src_V_last_V_0_sel_wr <= not(src_V_last_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    src_V_last_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_last_V_0_state <= ap_const_lv2_0;
            else
                if ((((src_V_last_V_0_state = ap_const_lv2_2) and (src_V_last_V_0_vld_in = ap_const_logic_0)) or ((src_V_last_V_0_state = ap_const_lv2_3) and (src_V_last_V_0_vld_in = ap_const_logic_0) and (src_V_last_V_0_ack_out = ap_const_logic_1)))) then 
                    src_V_last_V_0_state <= ap_const_lv2_2;
                elsif ((((src_V_last_V_0_state = ap_const_lv2_1) and (src_V_last_V_0_ack_out = ap_const_logic_0)) or ((src_V_last_V_0_state = ap_const_lv2_3) and (src_V_last_V_0_ack_out = ap_const_logic_0) and (src_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_last_V_0_state <= ap_const_lv2_1;
                elsif (((not(((src_V_last_V_0_vld_in = ap_const_logic_0) and (src_V_last_V_0_ack_out = ap_const_logic_1))) and not(((src_V_last_V_0_ack_out = ap_const_logic_0) and (src_V_last_V_0_vld_in = ap_const_logic_1))) and (src_V_last_V_0_state = ap_const_lv2_3)) or ((src_V_last_V_0_state = ap_const_lv2_1) and (src_V_last_V_0_ack_out = ap_const_logic_1)) or ((src_V_last_V_0_state = ap_const_lv2_2) and (src_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_last_V_0_state <= ap_const_lv2_3;
                else 
                    src_V_last_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    src_V_strb_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_strb_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((src_V_strb_V_0_ack_out = ap_const_logic_1) and (src_V_strb_V_0_vld_out = ap_const_logic_1))) then 
                                        src_V_strb_V_0_sel_rd <= not(src_V_strb_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    src_V_strb_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_strb_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((src_V_strb_V_0_ack_in = ap_const_logic_1) and (src_V_strb_V_0_vld_in = ap_const_logic_1))) then 
                                        src_V_strb_V_0_sel_wr <= not(src_V_strb_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    src_V_strb_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_strb_V_0_state <= ap_const_lv2_0;
            else
                if ((((src_V_strb_V_0_state = ap_const_lv2_2) and (src_V_strb_V_0_vld_in = ap_const_logic_0)) or ((src_V_strb_V_0_state = ap_const_lv2_3) and (src_V_strb_V_0_vld_in = ap_const_logic_0) and (src_V_strb_V_0_ack_out = ap_const_logic_1)))) then 
                    src_V_strb_V_0_state <= ap_const_lv2_2;
                elsif ((((src_V_strb_V_0_state = ap_const_lv2_1) and (src_V_strb_V_0_ack_out = ap_const_logic_0)) or ((src_V_strb_V_0_state = ap_const_lv2_3) and (src_V_strb_V_0_ack_out = ap_const_logic_0) and (src_V_strb_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_strb_V_0_state <= ap_const_lv2_1;
                elsif (((not(((src_V_strb_V_0_vld_in = ap_const_logic_0) and (src_V_strb_V_0_ack_out = ap_const_logic_1))) and not(((src_V_strb_V_0_ack_out = ap_const_logic_0) and (src_V_strb_V_0_vld_in = ap_const_logic_1))) and (src_V_strb_V_0_state = ap_const_lv2_3)) or ((src_V_strb_V_0_state = ap_const_lv2_1) and (src_V_strb_V_0_ack_out = ap_const_logic_1)) or ((src_V_strb_V_0_state = ap_const_lv2_2) and (src_V_strb_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_strb_V_0_state <= ap_const_lv2_3;
                else 
                    src_V_strb_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    src_V_user_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_user_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((src_V_user_V_0_ack_out = ap_const_logic_1) and (src_V_user_V_0_vld_out = ap_const_logic_1))) then 
                                        src_V_user_V_0_sel_rd <= not(src_V_user_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    src_V_user_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_user_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((src_V_user_V_0_ack_in = ap_const_logic_1) and (src_V_user_V_0_vld_in = ap_const_logic_1))) then 
                                        src_V_user_V_0_sel_wr <= not(src_V_user_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    src_V_user_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                src_V_user_V_0_state <= ap_const_lv2_0;
            else
                if ((((src_V_user_V_0_state = ap_const_lv2_2) and (src_V_user_V_0_vld_in = ap_const_logic_0)) or ((src_V_user_V_0_state = ap_const_lv2_3) and (src_V_user_V_0_vld_in = ap_const_logic_0) and (src_V_user_V_0_ack_out = ap_const_logic_1)))) then 
                    src_V_user_V_0_state <= ap_const_lv2_2;
                elsif ((((src_V_user_V_0_state = ap_const_lv2_1) and (src_V_user_V_0_ack_out = ap_const_logic_0)) or ((src_V_user_V_0_state = ap_const_lv2_3) and (src_V_user_V_0_ack_out = ap_const_logic_0) and (src_V_user_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_user_V_0_state <= ap_const_lv2_1;
                elsif (((not(((src_V_user_V_0_vld_in = ap_const_logic_0) and (src_V_user_V_0_ack_out = ap_const_logic_1))) and not(((src_V_user_V_0_ack_out = ap_const_logic_0) and (src_V_user_V_0_vld_in = ap_const_logic_1))) and (src_V_user_V_0_state = ap_const_lv2_3)) or ((src_V_user_V_0_state = ap_const_lv2_1) and (src_V_user_V_0_ack_out = ap_const_logic_1)) or ((src_V_user_V_0_state = ap_const_lv2_2) and (src_V_user_V_0_vld_in = ap_const_logic_1)))) then 
                    src_V_user_V_0_state <= ap_const_lv2_3;
                else 
                    src_V_user_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    x_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_924)) then
                if ((tmp_last_V_fu_144_p1 = ap_const_lv1_1)) then 
                    x <= ap_const_lv16_0;
                elsif ((tmp_last_V_fu_144_p1 = ap_const_lv1_0)) then 
                    x <= tmp_5_fu_205_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_data_V_1_load_A = ap_const_logic_1)) then
                dst_V_data_V_1_payload_A <= tmp_data_V_fu_196_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_data_V_1_load_B = ap_const_logic_1)) then
                dst_V_data_V_1_payload_B <= tmp_data_V_fu_196_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_dest_V_1_load_A = ap_const_logic_1)) then
                dst_V_dest_V_1_payload_A <= src_V_dest_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_dest_V_1_load_B = ap_const_logic_1)) then
                dst_V_dest_V_1_payload_B <= src_V_dest_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_id_V_1_load_A = ap_const_logic_1)) then
                dst_V_id_V_1_payload_A <= src_V_id_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_id_V_1_load_B = ap_const_logic_1)) then
                dst_V_id_V_1_payload_B <= src_V_id_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_keep_V_1_load_A = ap_const_logic_1)) then
                dst_V_keep_V_1_payload_A <= src_V_keep_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_keep_V_1_load_B = ap_const_logic_1)) then
                dst_V_keep_V_1_payload_B <= src_V_keep_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_last_V_1_load_A = ap_const_logic_1)) then
                dst_V_last_V_1_payload_A <= src_V_last_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_last_V_1_load_B = ap_const_logic_1)) then
                dst_V_last_V_1_payload_B <= src_V_last_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_strb_V_1_load_A = ap_const_logic_1)) then
                dst_V_strb_V_1_payload_A <= src_V_strb_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_strb_V_1_load_B = ap_const_logic_1)) then
                dst_V_strb_V_1_payload_B <= src_V_strb_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_user_V_1_load_A = ap_const_logic_1)) then
                dst_V_user_V_1_payload_A <= src_V_user_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((dst_V_user_V_1_load_B = ap_const_logic_1)) then
                dst_V_user_V_1_payload_B <= src_V_user_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mask_read_reg_239 <= mask;
                tmp_last_V_reg_259 <= src_V_last_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_data_V_0_load_A = ap_const_logic_1)) then
                src_V_data_V_0_payload_A <= src_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_data_V_0_load_B = ap_const_logic_1)) then
                src_V_data_V_0_payload_B <= src_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_dest_V_0_load_A = ap_const_logic_1)) then
                src_V_dest_V_0_payload_A <= src_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_dest_V_0_load_B = ap_const_logic_1)) then
                src_V_dest_V_0_payload_B <= src_TDEST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_id_V_0_load_A = ap_const_logic_1)) then
                src_V_id_V_0_payload_A <= src_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_id_V_0_load_B = ap_const_logic_1)) then
                src_V_id_V_0_payload_B <= src_TID;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_keep_V_0_load_A = ap_const_logic_1)) then
                src_V_keep_V_0_payload_A <= src_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_keep_V_0_load_B = ap_const_logic_1)) then
                src_V_keep_V_0_payload_B <= src_TKEEP;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_last_V_0_load_A = ap_const_logic_1)) then
                src_V_last_V_0_payload_A <= src_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_last_V_0_load_B = ap_const_logic_1)) then
                src_V_last_V_0_payload_B <= src_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_strb_V_0_load_A = ap_const_logic_1)) then
                src_V_strb_V_0_payload_A <= src_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_strb_V_0_load_B = ap_const_logic_1)) then
                src_V_strb_V_0_payload_B <= src_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_user_V_0_load_A = ap_const_logic_1)) then
                src_V_user_V_0_payload_A <= src_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((src_V_user_V_0_load_B = ap_const_logic_1)) then
                src_V_user_V_0_payload_B <= src_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_last_V_reg_259 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                y <= tmp_4_fu_227_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(src_V_data_V_0_vld_out, dst_V_data_V_1_ack_in, dst_V_keep_V_1_ack_in, dst_V_strb_V_1_ack_in, dst_V_user_V_1_ack_in, dst_V_last_V_1_ack_in, dst_V_id_V_1_ack_in, dst_V_dest_V_1_ack_in, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((dst_V_dest_V_1_ack_in = ap_const_logic_0) or (dst_V_id_V_1_ack_in = ap_const_logic_0) or (dst_V_last_V_1_ack_in = ap_const_logic_0) or (dst_V_user_V_1_ack_in = ap_const_logic_0) or (dst_V_strb_V_1_ack_in = ap_const_logic_0) or (dst_V_keep_V_1_ack_in = ap_const_logic_0) or (dst_V_data_V_1_ack_in = ap_const_logic_0))) or ((src_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(src_V_data_V_0_vld_out, dst_V_data_V_1_ack_in, dst_V_keep_V_1_ack_in, dst_V_strb_V_1_ack_in, dst_V_user_V_1_ack_in, dst_V_last_V_1_ack_in, dst_V_id_V_1_ack_in, dst_V_dest_V_1_ack_in, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((dst_V_dest_V_1_ack_in = ap_const_logic_0) or (dst_V_id_V_1_ack_in = ap_const_logic_0) or (dst_V_last_V_1_ack_in = ap_const_logic_0) or (dst_V_user_V_1_ack_in = ap_const_logic_0) or (dst_V_strb_V_1_ack_in = ap_const_logic_0) or (dst_V_keep_V_1_ack_in = ap_const_logic_0) or (dst_V_data_V_1_ack_in = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((dst_V_data_V_1_ack_in = ap_const_logic_0) or (src_V_data_V_0_vld_out = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(src_V_data_V_0_vld_out, dst_V_data_V_1_ack_in, dst_V_keep_V_1_ack_in, dst_V_strb_V_1_ack_in, dst_V_user_V_1_ack_in, dst_V_last_V_1_ack_in, dst_V_id_V_1_ack_in, dst_V_dest_V_1_ack_in, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((dst_V_dest_V_1_ack_in = ap_const_logic_0) or (dst_V_id_V_1_ack_in = ap_const_logic_0) or (dst_V_last_V_1_ack_in = ap_const_logic_0) or (dst_V_user_V_1_ack_in = ap_const_logic_0) or (dst_V_strb_V_1_ack_in = ap_const_logic_0) or (dst_V_keep_V_1_ack_in = ap_const_logic_0) or (dst_V_data_V_1_ack_in = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((dst_V_data_V_1_ack_in = ap_const_logic_0) or (src_V_data_V_0_vld_out = ap_const_logic_0))));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(src_V_data_V_0_vld_out)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (src_V_data_V_0_vld_out = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(dst_V_data_V_1_ack_in, dst_V_keep_V_1_ack_in, dst_V_strb_V_1_ack_in, dst_V_user_V_1_ack_in, dst_V_last_V_1_ack_in, dst_V_id_V_1_ack_in, dst_V_dest_V_1_ack_in)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((dst_V_dest_V_1_ack_in = ap_const_logic_0) or (dst_V_id_V_1_ack_in = ap_const_logic_0) or (dst_V_last_V_1_ack_in = ap_const_logic_0) or (dst_V_user_V_1_ack_in = ap_const_logic_0) or (dst_V_strb_V_1_ack_in = ap_const_logic_0) or (dst_V_keep_V_1_ack_in = ap_const_logic_0) or (dst_V_data_V_1_ack_in = ap_const_logic_0));
    end process;


    ap_condition_924_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_924 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    brmerge_fu_178_p2 <= (p_not1_fu_172_p2 or invert_fu_162_p2);
    dst_TDATA <= dst_V_data_V_1_data_out;

    dst_TDATA_blk_n_assign_proc : process(dst_V_data_V_1_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            dst_TDATA_blk_n <= dst_V_data_V_1_state(1);
        else 
            dst_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    dst_TDEST <= dst_V_dest_V_1_data_out;
    dst_TID <= dst_V_id_V_1_data_out;
    dst_TKEEP <= dst_V_keep_V_1_data_out;
    dst_TLAST <= dst_V_last_V_1_data_out;
    dst_TSTRB <= dst_V_strb_V_1_data_out;
    dst_TUSER <= dst_V_user_V_1_data_out;
    dst_TVALID <= dst_V_dest_V_1_state(0);
    dst_V_data_V_1_ack_in <= dst_V_data_V_1_state(1);
    dst_V_data_V_1_ack_out <= dst_TREADY;

    dst_V_data_V_1_data_out_assign_proc : process(dst_V_data_V_1_payload_A, dst_V_data_V_1_payload_B, dst_V_data_V_1_sel)
    begin
        if ((dst_V_data_V_1_sel = ap_const_logic_1)) then 
            dst_V_data_V_1_data_out <= dst_V_data_V_1_payload_B;
        else 
            dst_V_data_V_1_data_out <= dst_V_data_V_1_payload_A;
        end if; 
    end process;

    dst_V_data_V_1_load_A <= (not(dst_V_data_V_1_sel_wr) and dst_V_data_V_1_state_cmp_full);
    dst_V_data_V_1_load_B <= (dst_V_data_V_1_state_cmp_full and dst_V_data_V_1_sel_wr);
    dst_V_data_V_1_sel <= dst_V_data_V_1_sel_rd;
    dst_V_data_V_1_state_cmp_full <= '0' when (dst_V_data_V_1_state = ap_const_lv2_1) else '1';

    dst_V_data_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            dst_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_data_V_1_vld_out <= dst_V_data_V_1_state(0);
    dst_V_dest_V_1_ack_in <= dst_V_dest_V_1_state(1);
    dst_V_dest_V_1_ack_out <= dst_TREADY;

    dst_V_dest_V_1_data_out_assign_proc : process(dst_V_dest_V_1_payload_A, dst_V_dest_V_1_payload_B, dst_V_dest_V_1_sel)
    begin
        if ((dst_V_dest_V_1_sel = ap_const_logic_1)) then 
            dst_V_dest_V_1_data_out <= dst_V_dest_V_1_payload_B;
        else 
            dst_V_dest_V_1_data_out <= dst_V_dest_V_1_payload_A;
        end if; 
    end process;

    dst_V_dest_V_1_load_A <= (not(dst_V_dest_V_1_sel_wr) and dst_V_dest_V_1_state_cmp_full);
    dst_V_dest_V_1_load_B <= (dst_V_dest_V_1_state_cmp_full and dst_V_dest_V_1_sel_wr);
    dst_V_dest_V_1_sel <= dst_V_dest_V_1_sel_rd;
    dst_V_dest_V_1_state_cmp_full <= '0' when (dst_V_dest_V_1_state = ap_const_lv2_1) else '1';

    dst_V_dest_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_dest_V_1_vld_in <= ap_const_logic_1;
        else 
            dst_V_dest_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_dest_V_1_vld_out <= dst_V_dest_V_1_state(0);
    dst_V_id_V_1_ack_in <= dst_V_id_V_1_state(1);
    dst_V_id_V_1_ack_out <= dst_TREADY;

    dst_V_id_V_1_data_out_assign_proc : process(dst_V_id_V_1_payload_A, dst_V_id_V_1_payload_B, dst_V_id_V_1_sel)
    begin
        if ((dst_V_id_V_1_sel = ap_const_logic_1)) then 
            dst_V_id_V_1_data_out <= dst_V_id_V_1_payload_B;
        else 
            dst_V_id_V_1_data_out <= dst_V_id_V_1_payload_A;
        end if; 
    end process;

    dst_V_id_V_1_load_A <= (not(dst_V_id_V_1_sel_wr) and dst_V_id_V_1_state_cmp_full);
    dst_V_id_V_1_load_B <= (dst_V_id_V_1_state_cmp_full and dst_V_id_V_1_sel_wr);
    dst_V_id_V_1_sel <= dst_V_id_V_1_sel_rd;
    dst_V_id_V_1_state_cmp_full <= '0' when (dst_V_id_V_1_state = ap_const_lv2_1) else '1';

    dst_V_id_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_id_V_1_vld_in <= ap_const_logic_1;
        else 
            dst_V_id_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_id_V_1_vld_out <= dst_V_id_V_1_state(0);
    dst_V_keep_V_1_ack_in <= dst_V_keep_V_1_state(1);
    dst_V_keep_V_1_ack_out <= dst_TREADY;

    dst_V_keep_V_1_data_out_assign_proc : process(dst_V_keep_V_1_payload_A, dst_V_keep_V_1_payload_B, dst_V_keep_V_1_sel)
    begin
        if ((dst_V_keep_V_1_sel = ap_const_logic_1)) then 
            dst_V_keep_V_1_data_out <= dst_V_keep_V_1_payload_B;
        else 
            dst_V_keep_V_1_data_out <= dst_V_keep_V_1_payload_A;
        end if; 
    end process;

    dst_V_keep_V_1_load_A <= (not(dst_V_keep_V_1_sel_wr) and dst_V_keep_V_1_state_cmp_full);
    dst_V_keep_V_1_load_B <= (dst_V_keep_V_1_state_cmp_full and dst_V_keep_V_1_sel_wr);
    dst_V_keep_V_1_sel <= dst_V_keep_V_1_sel_rd;
    dst_V_keep_V_1_state_cmp_full <= '0' when (dst_V_keep_V_1_state = ap_const_lv2_1) else '1';

    dst_V_keep_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            dst_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_keep_V_1_vld_out <= dst_V_keep_V_1_state(0);
    dst_V_last_V_1_ack_in <= dst_V_last_V_1_state(1);
    dst_V_last_V_1_ack_out <= dst_TREADY;

    dst_V_last_V_1_data_out_assign_proc : process(dst_V_last_V_1_payload_A, dst_V_last_V_1_payload_B, dst_V_last_V_1_sel)
    begin
        if ((dst_V_last_V_1_sel = ap_const_logic_1)) then 
            dst_V_last_V_1_data_out <= dst_V_last_V_1_payload_B;
        else 
            dst_V_last_V_1_data_out <= dst_V_last_V_1_payload_A;
        end if; 
    end process;

    dst_V_last_V_1_load_A <= (not(dst_V_last_V_1_sel_wr) and dst_V_last_V_1_state_cmp_full);
    dst_V_last_V_1_load_B <= (dst_V_last_V_1_state_cmp_full and dst_V_last_V_1_sel_wr);
    dst_V_last_V_1_sel <= dst_V_last_V_1_sel_rd;
    dst_V_last_V_1_state_cmp_full <= '0' when (dst_V_last_V_1_state = ap_const_lv2_1) else '1';

    dst_V_last_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            dst_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_last_V_1_vld_out <= dst_V_last_V_1_state(0);
    dst_V_strb_V_1_ack_in <= dst_V_strb_V_1_state(1);
    dst_V_strb_V_1_ack_out <= dst_TREADY;

    dst_V_strb_V_1_data_out_assign_proc : process(dst_V_strb_V_1_payload_A, dst_V_strb_V_1_payload_B, dst_V_strb_V_1_sel)
    begin
        if ((dst_V_strb_V_1_sel = ap_const_logic_1)) then 
            dst_V_strb_V_1_data_out <= dst_V_strb_V_1_payload_B;
        else 
            dst_V_strb_V_1_data_out <= dst_V_strb_V_1_payload_A;
        end if; 
    end process;

    dst_V_strb_V_1_load_A <= (not(dst_V_strb_V_1_sel_wr) and dst_V_strb_V_1_state_cmp_full);
    dst_V_strb_V_1_load_B <= (dst_V_strb_V_1_state_cmp_full and dst_V_strb_V_1_sel_wr);
    dst_V_strb_V_1_sel <= dst_V_strb_V_1_sel_rd;
    dst_V_strb_V_1_state_cmp_full <= '0' when (dst_V_strb_V_1_state = ap_const_lv2_1) else '1';

    dst_V_strb_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_strb_V_1_vld_in <= ap_const_logic_1;
        else 
            dst_V_strb_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_strb_V_1_vld_out <= dst_V_strb_V_1_state(0);
    dst_V_user_V_1_ack_in <= dst_V_user_V_1_state(1);
    dst_V_user_V_1_ack_out <= dst_TREADY;

    dst_V_user_V_1_data_out_assign_proc : process(dst_V_user_V_1_payload_A, dst_V_user_V_1_payload_B, dst_V_user_V_1_sel)
    begin
        if ((dst_V_user_V_1_sel = ap_const_logic_1)) then 
            dst_V_user_V_1_data_out <= dst_V_user_V_1_payload_B;
        else 
            dst_V_user_V_1_data_out <= dst_V_user_V_1_payload_A;
        end if; 
    end process;

    dst_V_user_V_1_load_A <= (not(dst_V_user_V_1_sel_wr) and dst_V_user_V_1_state_cmp_full);
    dst_V_user_V_1_load_B <= (dst_V_user_V_1_state_cmp_full and dst_V_user_V_1_sel_wr);
    dst_V_user_V_1_sel <= dst_V_user_V_1_sel_rd;
    dst_V_user_V_1_state_cmp_full <= '0' when (dst_V_user_V_1_state = ap_const_lv2_1) else '1';

    dst_V_user_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_user_V_1_vld_in <= ap_const_logic_1;
        else 
            dst_V_user_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    dst_V_user_V_1_vld_out <= dst_V_user_V_1_state(0);
    invert_fu_162_p2 <= (tmp_fu_159_p1 xor ap_const_lv1_1);
    p_not1_fu_172_p2 <= "1" when (unsigned(x) < unsigned(ap_const_lv16_2B3)) else "0";
    p_not_fu_184_p2 <= (src_V_data_V_0_data_out or ap_const_lv32_FF000000);
    p_s_fu_190_p2 <= (p_not_fu_184_p2 xor ap_const_lv32_FFFFFF);

    src_TDATA_blk_n_assign_proc : process(src_V_data_V_0_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_TDATA_blk_n <= src_V_data_V_0_state(0);
        else 
            src_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    src_TREADY <= src_V_dest_V_0_state(1);
    src_V_data_V_0_ack_in <= src_V_data_V_0_state(1);

    src_V_data_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_V_data_V_0_ack_out <= ap_const_logic_1;
        else 
            src_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    src_V_data_V_0_data_out_assign_proc : process(src_V_data_V_0_payload_A, src_V_data_V_0_payload_B, src_V_data_V_0_sel)
    begin
        if ((src_V_data_V_0_sel = ap_const_logic_1)) then 
            src_V_data_V_0_data_out <= src_V_data_V_0_payload_B;
        else 
            src_V_data_V_0_data_out <= src_V_data_V_0_payload_A;
        end if; 
    end process;

    src_V_data_V_0_load_A <= (src_V_data_V_0_state_cmp_full and not(src_V_data_V_0_sel_wr));
    src_V_data_V_0_load_B <= (src_V_data_V_0_state_cmp_full and src_V_data_V_0_sel_wr);
    src_V_data_V_0_sel <= src_V_data_V_0_sel_rd;
    src_V_data_V_0_state_cmp_full <= '0' when (src_V_data_V_0_state = ap_const_lv2_1) else '1';
    src_V_data_V_0_vld_in <= src_TVALID;
    src_V_data_V_0_vld_out <= src_V_data_V_0_state(0);
    src_V_dest_V_0_ack_in <= src_V_dest_V_0_state(1);

    src_V_dest_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_V_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            src_V_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    src_V_dest_V_0_data_out_assign_proc : process(src_V_dest_V_0_payload_A, src_V_dest_V_0_payload_B, src_V_dest_V_0_sel)
    begin
        if ((src_V_dest_V_0_sel = ap_const_logic_1)) then 
            src_V_dest_V_0_data_out <= src_V_dest_V_0_payload_B;
        else 
            src_V_dest_V_0_data_out <= src_V_dest_V_0_payload_A;
        end if; 
    end process;

    src_V_dest_V_0_load_A <= (src_V_dest_V_0_state_cmp_full and not(src_V_dest_V_0_sel_wr));
    src_V_dest_V_0_load_B <= (src_V_dest_V_0_state_cmp_full and src_V_dest_V_0_sel_wr);
    src_V_dest_V_0_sel <= src_V_dest_V_0_sel_rd;
    src_V_dest_V_0_state_cmp_full <= '0' when (src_V_dest_V_0_state = ap_const_lv2_1) else '1';
    src_V_dest_V_0_vld_in <= src_TVALID;
    src_V_dest_V_0_vld_out <= src_V_dest_V_0_state(0);
    src_V_id_V_0_ack_in <= src_V_id_V_0_state(1);

    src_V_id_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_V_id_V_0_ack_out <= ap_const_logic_1;
        else 
            src_V_id_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    src_V_id_V_0_data_out_assign_proc : process(src_V_id_V_0_payload_A, src_V_id_V_0_payload_B, src_V_id_V_0_sel)
    begin
        if ((src_V_id_V_0_sel = ap_const_logic_1)) then 
            src_V_id_V_0_data_out <= src_V_id_V_0_payload_B;
        else 
            src_V_id_V_0_data_out <= src_V_id_V_0_payload_A;
        end if; 
    end process;

    src_V_id_V_0_load_A <= (src_V_id_V_0_state_cmp_full and not(src_V_id_V_0_sel_wr));
    src_V_id_V_0_load_B <= (src_V_id_V_0_state_cmp_full and src_V_id_V_0_sel_wr);
    src_V_id_V_0_sel <= src_V_id_V_0_sel_rd;
    src_V_id_V_0_state_cmp_full <= '0' when (src_V_id_V_0_state = ap_const_lv2_1) else '1';
    src_V_id_V_0_vld_in <= src_TVALID;
    src_V_id_V_0_vld_out <= src_V_id_V_0_state(0);
    src_V_keep_V_0_ack_in <= src_V_keep_V_0_state(1);

    src_V_keep_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_V_keep_V_0_ack_out <= ap_const_logic_1;
        else 
            src_V_keep_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    src_V_keep_V_0_data_out_assign_proc : process(src_V_keep_V_0_payload_A, src_V_keep_V_0_payload_B, src_V_keep_V_0_sel)
    begin
        if ((src_V_keep_V_0_sel = ap_const_logic_1)) then 
            src_V_keep_V_0_data_out <= src_V_keep_V_0_payload_B;
        else 
            src_V_keep_V_0_data_out <= src_V_keep_V_0_payload_A;
        end if; 
    end process;

    src_V_keep_V_0_load_A <= (src_V_keep_V_0_state_cmp_full and not(src_V_keep_V_0_sel_wr));
    src_V_keep_V_0_load_B <= (src_V_keep_V_0_state_cmp_full and src_V_keep_V_0_sel_wr);
    src_V_keep_V_0_sel <= src_V_keep_V_0_sel_rd;
    src_V_keep_V_0_state_cmp_full <= '0' when (src_V_keep_V_0_state = ap_const_lv2_1) else '1';
    src_V_keep_V_0_vld_in <= src_TVALID;
    src_V_keep_V_0_vld_out <= src_V_keep_V_0_state(0);
    src_V_last_V_0_ack_in <= src_V_last_V_0_state(1);

    src_V_last_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_V_last_V_0_ack_out <= ap_const_logic_1;
        else 
            src_V_last_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    src_V_last_V_0_data_out_assign_proc : process(src_V_last_V_0_payload_A, src_V_last_V_0_payload_B, src_V_last_V_0_sel)
    begin
        if ((src_V_last_V_0_sel = ap_const_logic_1)) then 
            src_V_last_V_0_data_out <= src_V_last_V_0_payload_B;
        else 
            src_V_last_V_0_data_out <= src_V_last_V_0_payload_A;
        end if; 
    end process;

    src_V_last_V_0_load_A <= (src_V_last_V_0_state_cmp_full and not(src_V_last_V_0_sel_wr));
    src_V_last_V_0_load_B <= (src_V_last_V_0_state_cmp_full and src_V_last_V_0_sel_wr);
    src_V_last_V_0_sel <= src_V_last_V_0_sel_rd;
    src_V_last_V_0_state_cmp_full <= '0' when (src_V_last_V_0_state = ap_const_lv2_1) else '1';
    src_V_last_V_0_vld_in <= src_TVALID;
    src_V_last_V_0_vld_out <= src_V_last_V_0_state(0);
    src_V_strb_V_0_ack_in <= src_V_strb_V_0_state(1);

    src_V_strb_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_V_strb_V_0_ack_out <= ap_const_logic_1;
        else 
            src_V_strb_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    src_V_strb_V_0_data_out_assign_proc : process(src_V_strb_V_0_payload_A, src_V_strb_V_0_payload_B, src_V_strb_V_0_sel)
    begin
        if ((src_V_strb_V_0_sel = ap_const_logic_1)) then 
            src_V_strb_V_0_data_out <= src_V_strb_V_0_payload_B;
        else 
            src_V_strb_V_0_data_out <= src_V_strb_V_0_payload_A;
        end if; 
    end process;

    src_V_strb_V_0_load_A <= (src_V_strb_V_0_state_cmp_full and not(src_V_strb_V_0_sel_wr));
    src_V_strb_V_0_load_B <= (src_V_strb_V_0_state_cmp_full and src_V_strb_V_0_sel_wr);
    src_V_strb_V_0_sel <= src_V_strb_V_0_sel_rd;
    src_V_strb_V_0_state_cmp_full <= '0' when (src_V_strb_V_0_state = ap_const_lv2_1) else '1';
    src_V_strb_V_0_vld_in <= src_TVALID;
    src_V_strb_V_0_vld_out <= src_V_strb_V_0_state(0);
    src_V_user_V_0_ack_in <= src_V_user_V_0_state(1);

    src_V_user_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            src_V_user_V_0_ack_out <= ap_const_logic_1;
        else 
            src_V_user_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    src_V_user_V_0_data_out_assign_proc : process(src_V_user_V_0_payload_A, src_V_user_V_0_payload_B, src_V_user_V_0_sel)
    begin
        if ((src_V_user_V_0_sel = ap_const_logic_1)) then 
            src_V_user_V_0_data_out <= src_V_user_V_0_payload_B;
        else 
            src_V_user_V_0_data_out <= src_V_user_V_0_payload_A;
        end if; 
    end process;

    src_V_user_V_0_load_A <= (src_V_user_V_0_state_cmp_full and not(src_V_user_V_0_sel_wr));
    src_V_user_V_0_load_B <= (src_V_user_V_0_state_cmp_full and src_V_user_V_0_sel_wr);
    src_V_user_V_0_sel <= src_V_user_V_0_sel_rd;
    src_V_user_V_0_state_cmp_full <= '0' when (src_V_user_V_0_state = ap_const_lv2_1) else '1';
    src_V_user_V_0_vld_in <= src_TVALID;
    src_V_user_V_0_vld_out <= src_V_user_V_0_state(0);
    tmp_4_fu_227_p2 <= std_logic_vector(unsigned(y) + unsigned(ap_const_lv16_1));
    tmp_5_fu_205_p2 <= std_logic_vector(unsigned(x) + unsigned(ap_const_lv16_1));
    tmp_data_V_fu_196_p3 <= 
        src_V_data_V_0_data_out when (brmerge_fu_178_p2(0) = '1') else 
        p_s_fu_190_p2;
    tmp_fu_159_p1 <= mask_read_reg_239(1 - 1 downto 0);
    tmp_last_V_fu_144_p1 <= src_V_last_V_0_data_out;
end behav;
