// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="stream,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.846000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=368,HLS_SYN_LUT=804,HLS_VERSION=2018_2}" *)

module stream (
        ap_clk,
        ap_rst_n,
        src_TDATA,
        src_TVALID,
        src_TREADY,
        src_TKEEP,
        src_TSTRB,
        src_TUSER,
        src_TLAST,
        src_TID,
        src_TDEST,
        dst_TDATA,
        dst_TVALID,
        dst_TREADY,
        dst_TKEEP,
        dst_TSTRB,
        dst_TUSER,
        dst_TLAST,
        dst_TID,
        dst_TDEST,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] src_TDATA;
input   src_TVALID;
output   src_TREADY;
input  [3:0] src_TKEEP;
input  [3:0] src_TSTRB;
input  [0:0] src_TUSER;
input  [0:0] src_TLAST;
input  [0:0] src_TID;
input  [0:0] src_TDEST;
output  [31:0] dst_TDATA;
output   dst_TVALID;
input   dst_TREADY;
output  [3:0] dst_TKEEP;
output  [3:0] dst_TSTRB;
output  [0:0] dst_TUSER;
output  [0:0] dst_TLAST;
output  [0:0] dst_TID;
output  [0:0] dst_TDEST;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;

 reg    ap_rst_n_inv;
reg   [31:0] src_V_data_V_0_data_out;
wire    src_V_data_V_0_vld_in;
wire    src_V_data_V_0_vld_out;
wire    src_V_data_V_0_ack_in;
reg    src_V_data_V_0_ack_out;
reg   [31:0] src_V_data_V_0_payload_A;
reg   [31:0] src_V_data_V_0_payload_B;
reg    src_V_data_V_0_sel_rd;
reg    src_V_data_V_0_sel_wr;
wire    src_V_data_V_0_sel;
wire    src_V_data_V_0_load_A;
wire    src_V_data_V_0_load_B;
reg   [1:0] src_V_data_V_0_state;
wire    src_V_data_V_0_state_cmp_full;
reg   [3:0] src_V_keep_V_0_data_out;
wire    src_V_keep_V_0_vld_in;
wire    src_V_keep_V_0_vld_out;
wire    src_V_keep_V_0_ack_in;
reg    src_V_keep_V_0_ack_out;
reg   [3:0] src_V_keep_V_0_payload_A;
reg   [3:0] src_V_keep_V_0_payload_B;
reg    src_V_keep_V_0_sel_rd;
reg    src_V_keep_V_0_sel_wr;
wire    src_V_keep_V_0_sel;
wire    src_V_keep_V_0_load_A;
wire    src_V_keep_V_0_load_B;
reg   [1:0] src_V_keep_V_0_state;
wire    src_V_keep_V_0_state_cmp_full;
reg   [3:0] src_V_strb_V_0_data_out;
wire    src_V_strb_V_0_vld_in;
wire    src_V_strb_V_0_vld_out;
wire    src_V_strb_V_0_ack_in;
reg    src_V_strb_V_0_ack_out;
reg   [3:0] src_V_strb_V_0_payload_A;
reg   [3:0] src_V_strb_V_0_payload_B;
reg    src_V_strb_V_0_sel_rd;
reg    src_V_strb_V_0_sel_wr;
wire    src_V_strb_V_0_sel;
wire    src_V_strb_V_0_load_A;
wire    src_V_strb_V_0_load_B;
reg   [1:0] src_V_strb_V_0_state;
wire    src_V_strb_V_0_state_cmp_full;
reg   [0:0] src_V_user_V_0_data_out;
wire    src_V_user_V_0_vld_in;
wire    src_V_user_V_0_vld_out;
wire    src_V_user_V_0_ack_in;
reg    src_V_user_V_0_ack_out;
reg   [0:0] src_V_user_V_0_payload_A;
reg   [0:0] src_V_user_V_0_payload_B;
reg    src_V_user_V_0_sel_rd;
reg    src_V_user_V_0_sel_wr;
wire    src_V_user_V_0_sel;
wire    src_V_user_V_0_load_A;
wire    src_V_user_V_0_load_B;
reg   [1:0] src_V_user_V_0_state;
wire    src_V_user_V_0_state_cmp_full;
reg   [0:0] src_V_last_V_0_data_out;
wire    src_V_last_V_0_vld_in;
wire    src_V_last_V_0_vld_out;
wire    src_V_last_V_0_ack_in;
reg    src_V_last_V_0_ack_out;
reg   [0:0] src_V_last_V_0_payload_A;
reg   [0:0] src_V_last_V_0_payload_B;
reg    src_V_last_V_0_sel_rd;
reg    src_V_last_V_0_sel_wr;
wire    src_V_last_V_0_sel;
wire    src_V_last_V_0_load_A;
wire    src_V_last_V_0_load_B;
reg   [1:0] src_V_last_V_0_state;
wire    src_V_last_V_0_state_cmp_full;
reg   [0:0] src_V_id_V_0_data_out;
wire    src_V_id_V_0_vld_in;
wire    src_V_id_V_0_vld_out;
wire    src_V_id_V_0_ack_in;
reg    src_V_id_V_0_ack_out;
reg   [0:0] src_V_id_V_0_payload_A;
reg   [0:0] src_V_id_V_0_payload_B;
reg    src_V_id_V_0_sel_rd;
reg    src_V_id_V_0_sel_wr;
wire    src_V_id_V_0_sel;
wire    src_V_id_V_0_load_A;
wire    src_V_id_V_0_load_B;
reg   [1:0] src_V_id_V_0_state;
wire    src_V_id_V_0_state_cmp_full;
reg   [0:0] src_V_dest_V_0_data_out;
wire    src_V_dest_V_0_vld_in;
wire    src_V_dest_V_0_vld_out;
wire    src_V_dest_V_0_ack_in;
reg    src_V_dest_V_0_ack_out;
reg   [0:0] src_V_dest_V_0_payload_A;
reg   [0:0] src_V_dest_V_0_payload_B;
reg    src_V_dest_V_0_sel_rd;
reg    src_V_dest_V_0_sel_wr;
wire    src_V_dest_V_0_sel;
wire    src_V_dest_V_0_load_A;
wire    src_V_dest_V_0_load_B;
reg   [1:0] src_V_dest_V_0_state;
wire    src_V_dest_V_0_state_cmp_full;
reg   [31:0] dst_V_data_V_1_data_out;
reg    dst_V_data_V_1_vld_in;
wire    dst_V_data_V_1_vld_out;
wire    dst_V_data_V_1_ack_in;
wire    dst_V_data_V_1_ack_out;
reg   [31:0] dst_V_data_V_1_payload_A;
reg   [31:0] dst_V_data_V_1_payload_B;
reg    dst_V_data_V_1_sel_rd;
reg    dst_V_data_V_1_sel_wr;
wire    dst_V_data_V_1_sel;
wire    dst_V_data_V_1_load_A;
wire    dst_V_data_V_1_load_B;
reg   [1:0] dst_V_data_V_1_state;
wire    dst_V_data_V_1_state_cmp_full;
reg   [3:0] dst_V_keep_V_1_data_out;
reg    dst_V_keep_V_1_vld_in;
wire    dst_V_keep_V_1_vld_out;
wire    dst_V_keep_V_1_ack_in;
wire    dst_V_keep_V_1_ack_out;
reg   [3:0] dst_V_keep_V_1_payload_A;
reg   [3:0] dst_V_keep_V_1_payload_B;
reg    dst_V_keep_V_1_sel_rd;
reg    dst_V_keep_V_1_sel_wr;
wire    dst_V_keep_V_1_sel;
wire    dst_V_keep_V_1_load_A;
wire    dst_V_keep_V_1_load_B;
reg   [1:0] dst_V_keep_V_1_state;
wire    dst_V_keep_V_1_state_cmp_full;
reg   [3:0] dst_V_strb_V_1_data_out;
reg    dst_V_strb_V_1_vld_in;
wire    dst_V_strb_V_1_vld_out;
wire    dst_V_strb_V_1_ack_in;
wire    dst_V_strb_V_1_ack_out;
reg   [3:0] dst_V_strb_V_1_payload_A;
reg   [3:0] dst_V_strb_V_1_payload_B;
reg    dst_V_strb_V_1_sel_rd;
reg    dst_V_strb_V_1_sel_wr;
wire    dst_V_strb_V_1_sel;
wire    dst_V_strb_V_1_load_A;
wire    dst_V_strb_V_1_load_B;
reg   [1:0] dst_V_strb_V_1_state;
wire    dst_V_strb_V_1_state_cmp_full;
reg   [0:0] dst_V_user_V_1_data_out;
reg    dst_V_user_V_1_vld_in;
wire    dst_V_user_V_1_vld_out;
wire    dst_V_user_V_1_ack_in;
wire    dst_V_user_V_1_ack_out;
reg   [0:0] dst_V_user_V_1_payload_A;
reg   [0:0] dst_V_user_V_1_payload_B;
reg    dst_V_user_V_1_sel_rd;
reg    dst_V_user_V_1_sel_wr;
wire    dst_V_user_V_1_sel;
wire    dst_V_user_V_1_load_A;
wire    dst_V_user_V_1_load_B;
reg   [1:0] dst_V_user_V_1_state;
wire    dst_V_user_V_1_state_cmp_full;
reg   [0:0] dst_V_last_V_1_data_out;
reg    dst_V_last_V_1_vld_in;
wire    dst_V_last_V_1_vld_out;
wire    dst_V_last_V_1_ack_in;
wire    dst_V_last_V_1_ack_out;
reg   [0:0] dst_V_last_V_1_payload_A;
reg   [0:0] dst_V_last_V_1_payload_B;
reg    dst_V_last_V_1_sel_rd;
reg    dst_V_last_V_1_sel_wr;
wire    dst_V_last_V_1_sel;
wire    dst_V_last_V_1_load_A;
wire    dst_V_last_V_1_load_B;
reg   [1:0] dst_V_last_V_1_state;
wire    dst_V_last_V_1_state_cmp_full;
reg   [0:0] dst_V_id_V_1_data_out;
reg    dst_V_id_V_1_vld_in;
wire    dst_V_id_V_1_vld_out;
wire    dst_V_id_V_1_ack_in;
wire    dst_V_id_V_1_ack_out;
reg   [0:0] dst_V_id_V_1_payload_A;
reg   [0:0] dst_V_id_V_1_payload_B;
reg    dst_V_id_V_1_sel_rd;
reg    dst_V_id_V_1_sel_wr;
wire    dst_V_id_V_1_sel;
wire    dst_V_id_V_1_load_A;
wire    dst_V_id_V_1_load_B;
reg   [1:0] dst_V_id_V_1_state;
wire    dst_V_id_V_1_state_cmp_full;
reg   [0:0] dst_V_dest_V_1_data_out;
reg    dst_V_dest_V_1_vld_in;
wire    dst_V_dest_V_1_vld_out;
wire    dst_V_dest_V_1_ack_in;
wire    dst_V_dest_V_1_ack_out;
reg   [0:0] dst_V_dest_V_1_payload_A;
reg   [0:0] dst_V_dest_V_1_payload_B;
reg    dst_V_dest_V_1_sel_rd;
reg    dst_V_dest_V_1_sel_wr;
wire    dst_V_dest_V_1_sel;
wire    dst_V_dest_V_1_load_A;
wire    dst_V_dest_V_1_load_B;
reg   [1:0] dst_V_dest_V_1_state;
wire    dst_V_dest_V_1_state_cmp_full;
wire   [31:0] mask;
reg   [15:0] x;
reg   [15:0] y;
reg    src_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    dst_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [31:0] mask_read_reg_239;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_last_V_fu_144_p1;
reg   [0:0] tmp_last_V_reg_259;
wire   [31:0] tmp_data_V_fu_196_p3;
reg    ap_block_pp0_stage0_subdone;
wire   [15:0] tmp_5_fu_205_p2;
wire   [15:0] tmp_4_fu_227_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_fu_159_p1;
wire   [0:0] p_not1_fu_172_p2;
wire   [0:0] invert_fu_162_p2;
wire   [31:0] p_not_fu_184_p2;
wire   [0:0] brmerge_fu_178_p2;
wire   [31:0] p_s_fu_190_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_924;

// power-on initialization
initial begin
#0 src_V_data_V_0_sel_rd = 1'b0;
#0 src_V_data_V_0_sel_wr = 1'b0;
#0 src_V_data_V_0_state = 2'd0;
#0 src_V_keep_V_0_sel_rd = 1'b0;
#0 src_V_keep_V_0_sel_wr = 1'b0;
#0 src_V_keep_V_0_state = 2'd0;
#0 src_V_strb_V_0_sel_rd = 1'b0;
#0 src_V_strb_V_0_sel_wr = 1'b0;
#0 src_V_strb_V_0_state = 2'd0;
#0 src_V_user_V_0_sel_rd = 1'b0;
#0 src_V_user_V_0_sel_wr = 1'b0;
#0 src_V_user_V_0_state = 2'd0;
#0 src_V_last_V_0_sel_rd = 1'b0;
#0 src_V_last_V_0_sel_wr = 1'b0;
#0 src_V_last_V_0_state = 2'd0;
#0 src_V_id_V_0_sel_rd = 1'b0;
#0 src_V_id_V_0_sel_wr = 1'b0;
#0 src_V_id_V_0_state = 2'd0;
#0 src_V_dest_V_0_sel_rd = 1'b0;
#0 src_V_dest_V_0_sel_wr = 1'b0;
#0 src_V_dest_V_0_state = 2'd0;
#0 dst_V_data_V_1_sel_rd = 1'b0;
#0 dst_V_data_V_1_sel_wr = 1'b0;
#0 dst_V_data_V_1_state = 2'd0;
#0 dst_V_keep_V_1_sel_rd = 1'b0;
#0 dst_V_keep_V_1_sel_wr = 1'b0;
#0 dst_V_keep_V_1_state = 2'd0;
#0 dst_V_strb_V_1_sel_rd = 1'b0;
#0 dst_V_strb_V_1_sel_wr = 1'b0;
#0 dst_V_strb_V_1_state = 2'd0;
#0 dst_V_user_V_1_sel_rd = 1'b0;
#0 dst_V_user_V_1_sel_wr = 1'b0;
#0 dst_V_user_V_1_state = 2'd0;
#0 dst_V_last_V_1_sel_rd = 1'b0;
#0 dst_V_last_V_1_sel_wr = 1'b0;
#0 dst_V_last_V_1_state = 2'd0;
#0 dst_V_id_V_1_sel_rd = 1'b0;
#0 dst_V_id_V_1_sel_wr = 1'b0;
#0 dst_V_id_V_1_state = 2'd0;
#0 dst_V_dest_V_1_sel_rd = 1'b0;
#0 dst_V_dest_V_1_sel_wr = 1'b0;
#0 dst_V_dest_V_1_state = 2'd0;
#0 x = 16'd0;
#0 y = 16'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

stream_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
stream_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mask(mask)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_V_data_V_1_ack_out == 1'b1) & (dst_V_data_V_1_vld_out == 1'b1))) begin
            dst_V_data_V_1_sel_rd <= ~dst_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_V_data_V_1_ack_in == 1'b1) & (dst_V_data_V_1_vld_in == 1'b1))) begin
            dst_V_data_V_1_sel_wr <= ~dst_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((dst_V_data_V_1_state == 2'd2) & (dst_V_data_V_1_vld_in == 1'b0)) | ((dst_V_data_V_1_state == 2'd3) & (dst_V_data_V_1_vld_in == 1'b0) & (dst_V_data_V_1_ack_out == 1'b1)))) begin
            dst_V_data_V_1_state <= 2'd2;
        end else if ((((dst_V_data_V_1_state == 2'd1) & (dst_V_data_V_1_ack_out == 1'b0)) | ((dst_V_data_V_1_state == 2'd3) & (dst_V_data_V_1_ack_out == 1'b0) & (dst_V_data_V_1_vld_in == 1'b1)))) begin
            dst_V_data_V_1_state <= 2'd1;
        end else if (((~((dst_V_data_V_1_vld_in == 1'b0) & (dst_V_data_V_1_ack_out == 1'b1)) & ~((dst_V_data_V_1_ack_out == 1'b0) & (dst_V_data_V_1_vld_in == 1'b1)) & (dst_V_data_V_1_state == 2'd3)) | ((dst_V_data_V_1_state == 2'd1) & (dst_V_data_V_1_ack_out == 1'b1)) | ((dst_V_data_V_1_state == 2'd2) & (dst_V_data_V_1_vld_in == 1'b1)))) begin
            dst_V_data_V_1_state <= 2'd3;
        end else begin
            dst_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_V_dest_V_1_ack_out == 1'b1) & (dst_V_dest_V_1_vld_out == 1'b1))) begin
            dst_V_dest_V_1_sel_rd <= ~dst_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_dest_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_V_dest_V_1_ack_in == 1'b1) & (dst_V_dest_V_1_vld_in == 1'b1))) begin
            dst_V_dest_V_1_sel_wr <= ~dst_V_dest_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_dest_V_1_state <= 2'd0;
    end else begin
        if ((((dst_V_dest_V_1_state == 2'd2) & (dst_V_dest_V_1_vld_in == 1'b0)) | ((dst_V_dest_V_1_state == 2'd3) & (dst_V_dest_V_1_vld_in == 1'b0) & (dst_V_dest_V_1_ack_out == 1'b1)))) begin
            dst_V_dest_V_1_state <= 2'd2;
        end else if ((((dst_V_dest_V_1_state == 2'd1) & (dst_V_dest_V_1_ack_out == 1'b0)) | ((dst_V_dest_V_1_state == 2'd3) & (dst_V_dest_V_1_ack_out == 1'b0) & (dst_V_dest_V_1_vld_in == 1'b1)))) begin
            dst_V_dest_V_1_state <= 2'd1;
        end else if (((~((dst_V_dest_V_1_vld_in == 1'b0) & (dst_V_dest_V_1_ack_out == 1'b1)) & ~((dst_V_dest_V_1_ack_out == 1'b0) & (dst_V_dest_V_1_vld_in == 1'b1)) & (dst_V_dest_V_1_state == 2'd3)) | ((dst_V_dest_V_1_state == 2'd1) & (dst_V_dest_V_1_ack_out == 1'b1)) | ((dst_V_dest_V_1_state == 2'd2) & (dst_V_dest_V_1_vld_in == 1'b1)))) begin
            dst_V_dest_V_1_state <= 2'd3;
        end else begin
            dst_V_dest_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_V_id_V_1_ack_out == 1'b1) & (dst_V_id_V_1_vld_out == 1'b1))) begin
            dst_V_id_V_1_sel_rd <= ~dst_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_id_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_V_id_V_1_ack_in == 1'b1) & (dst_V_id_V_1_vld_in == 1'b1))) begin
            dst_V_id_V_1_sel_wr <= ~dst_V_id_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_id_V_1_state <= 2'd0;
    end else begin
        if ((((dst_V_id_V_1_state == 2'd2) & (dst_V_id_V_1_vld_in == 1'b0)) | ((dst_V_id_V_1_state == 2'd3) & (dst_V_id_V_1_vld_in == 1'b0) & (dst_V_id_V_1_ack_out == 1'b1)))) begin
            dst_V_id_V_1_state <= 2'd2;
        end else if ((((dst_V_id_V_1_state == 2'd1) & (dst_V_id_V_1_ack_out == 1'b0)) | ((dst_V_id_V_1_state == 2'd3) & (dst_V_id_V_1_ack_out == 1'b0) & (dst_V_id_V_1_vld_in == 1'b1)))) begin
            dst_V_id_V_1_state <= 2'd1;
        end else if (((~((dst_V_id_V_1_vld_in == 1'b0) & (dst_V_id_V_1_ack_out == 1'b1)) & ~((dst_V_id_V_1_ack_out == 1'b0) & (dst_V_id_V_1_vld_in == 1'b1)) & (dst_V_id_V_1_state == 2'd3)) | ((dst_V_id_V_1_state == 2'd1) & (dst_V_id_V_1_ack_out == 1'b1)) | ((dst_V_id_V_1_state == 2'd2) & (dst_V_id_V_1_vld_in == 1'b1)))) begin
            dst_V_id_V_1_state <= 2'd3;
        end else begin
            dst_V_id_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_V_keep_V_1_ack_out == 1'b1) & (dst_V_keep_V_1_vld_out == 1'b1))) begin
            dst_V_keep_V_1_sel_rd <= ~dst_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_keep_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_V_keep_V_1_ack_in == 1'b1) & (dst_V_keep_V_1_vld_in == 1'b1))) begin
            dst_V_keep_V_1_sel_wr <= ~dst_V_keep_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((dst_V_keep_V_1_state == 2'd2) & (dst_V_keep_V_1_vld_in == 1'b0)) | ((dst_V_keep_V_1_state == 2'd3) & (dst_V_keep_V_1_vld_in == 1'b0) & (dst_V_keep_V_1_ack_out == 1'b1)))) begin
            dst_V_keep_V_1_state <= 2'd2;
        end else if ((((dst_V_keep_V_1_state == 2'd1) & (dst_V_keep_V_1_ack_out == 1'b0)) | ((dst_V_keep_V_1_state == 2'd3) & (dst_V_keep_V_1_ack_out == 1'b0) & (dst_V_keep_V_1_vld_in == 1'b1)))) begin
            dst_V_keep_V_1_state <= 2'd1;
        end else if (((~((dst_V_keep_V_1_vld_in == 1'b0) & (dst_V_keep_V_1_ack_out == 1'b1)) & ~((dst_V_keep_V_1_ack_out == 1'b0) & (dst_V_keep_V_1_vld_in == 1'b1)) & (dst_V_keep_V_1_state == 2'd3)) | ((dst_V_keep_V_1_state == 2'd1) & (dst_V_keep_V_1_ack_out == 1'b1)) | ((dst_V_keep_V_1_state == 2'd2) & (dst_V_keep_V_1_vld_in == 1'b1)))) begin
            dst_V_keep_V_1_state <= 2'd3;
        end else begin
            dst_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_V_last_V_1_ack_out == 1'b1) & (dst_V_last_V_1_vld_out == 1'b1))) begin
            dst_V_last_V_1_sel_rd <= ~dst_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_V_last_V_1_ack_in == 1'b1) & (dst_V_last_V_1_vld_in == 1'b1))) begin
            dst_V_last_V_1_sel_wr <= ~dst_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((dst_V_last_V_1_state == 2'd2) & (dst_V_last_V_1_vld_in == 1'b0)) | ((dst_V_last_V_1_state == 2'd3) & (dst_V_last_V_1_vld_in == 1'b0) & (dst_V_last_V_1_ack_out == 1'b1)))) begin
            dst_V_last_V_1_state <= 2'd2;
        end else if ((((dst_V_last_V_1_state == 2'd1) & (dst_V_last_V_1_ack_out == 1'b0)) | ((dst_V_last_V_1_state == 2'd3) & (dst_V_last_V_1_ack_out == 1'b0) & (dst_V_last_V_1_vld_in == 1'b1)))) begin
            dst_V_last_V_1_state <= 2'd1;
        end else if (((~((dst_V_last_V_1_vld_in == 1'b0) & (dst_V_last_V_1_ack_out == 1'b1)) & ~((dst_V_last_V_1_ack_out == 1'b0) & (dst_V_last_V_1_vld_in == 1'b1)) & (dst_V_last_V_1_state == 2'd3)) | ((dst_V_last_V_1_state == 2'd1) & (dst_V_last_V_1_ack_out == 1'b1)) | ((dst_V_last_V_1_state == 2'd2) & (dst_V_last_V_1_vld_in == 1'b1)))) begin
            dst_V_last_V_1_state <= 2'd3;
        end else begin
            dst_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_V_strb_V_1_ack_out == 1'b1) & (dst_V_strb_V_1_vld_out == 1'b1))) begin
            dst_V_strb_V_1_sel_rd <= ~dst_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_strb_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_V_strb_V_1_ack_in == 1'b1) & (dst_V_strb_V_1_vld_in == 1'b1))) begin
            dst_V_strb_V_1_sel_wr <= ~dst_V_strb_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((dst_V_strb_V_1_state == 2'd2) & (dst_V_strb_V_1_vld_in == 1'b0)) | ((dst_V_strb_V_1_state == 2'd3) & (dst_V_strb_V_1_vld_in == 1'b0) & (dst_V_strb_V_1_ack_out == 1'b1)))) begin
            dst_V_strb_V_1_state <= 2'd2;
        end else if ((((dst_V_strb_V_1_state == 2'd1) & (dst_V_strb_V_1_ack_out == 1'b0)) | ((dst_V_strb_V_1_state == 2'd3) & (dst_V_strb_V_1_ack_out == 1'b0) & (dst_V_strb_V_1_vld_in == 1'b1)))) begin
            dst_V_strb_V_1_state <= 2'd1;
        end else if (((~((dst_V_strb_V_1_vld_in == 1'b0) & (dst_V_strb_V_1_ack_out == 1'b1)) & ~((dst_V_strb_V_1_ack_out == 1'b0) & (dst_V_strb_V_1_vld_in == 1'b1)) & (dst_V_strb_V_1_state == 2'd3)) | ((dst_V_strb_V_1_state == 2'd1) & (dst_V_strb_V_1_ack_out == 1'b1)) | ((dst_V_strb_V_1_state == 2'd2) & (dst_V_strb_V_1_vld_in == 1'b1)))) begin
            dst_V_strb_V_1_state <= 2'd3;
        end else begin
            dst_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((dst_V_user_V_1_ack_out == 1'b1) & (dst_V_user_V_1_vld_out == 1'b1))) begin
            dst_V_user_V_1_sel_rd <= ~dst_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((dst_V_user_V_1_ack_in == 1'b1) & (dst_V_user_V_1_vld_in == 1'b1))) begin
            dst_V_user_V_1_sel_wr <= ~dst_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        dst_V_user_V_1_state <= 2'd0;
    end else begin
        if ((((dst_V_user_V_1_state == 2'd2) & (dst_V_user_V_1_vld_in == 1'b0)) | ((dst_V_user_V_1_state == 2'd3) & (dst_V_user_V_1_vld_in == 1'b0) & (dst_V_user_V_1_ack_out == 1'b1)))) begin
            dst_V_user_V_1_state <= 2'd2;
        end else if ((((dst_V_user_V_1_state == 2'd1) & (dst_V_user_V_1_ack_out == 1'b0)) | ((dst_V_user_V_1_state == 2'd3) & (dst_V_user_V_1_ack_out == 1'b0) & (dst_V_user_V_1_vld_in == 1'b1)))) begin
            dst_V_user_V_1_state <= 2'd1;
        end else if (((~((dst_V_user_V_1_vld_in == 1'b0) & (dst_V_user_V_1_ack_out == 1'b1)) & ~((dst_V_user_V_1_ack_out == 1'b0) & (dst_V_user_V_1_vld_in == 1'b1)) & (dst_V_user_V_1_state == 2'd3)) | ((dst_V_user_V_1_state == 2'd1) & (dst_V_user_V_1_ack_out == 1'b1)) | ((dst_V_user_V_1_state == 2'd2) & (dst_V_user_V_1_vld_in == 1'b1)))) begin
            dst_V_user_V_1_state <= 2'd3;
        end else begin
            dst_V_user_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_V_data_V_0_ack_out == 1'b1) & (src_V_data_V_0_vld_out == 1'b1))) begin
            src_V_data_V_0_sel_rd <= ~src_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_V_data_V_0_ack_in == 1'b1) & (src_V_data_V_0_vld_in == 1'b1))) begin
            src_V_data_V_0_sel_wr <= ~src_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((src_V_data_V_0_vld_in == 1'b0) & (src_V_data_V_0_state == 2'd2)) | ((src_V_data_V_0_vld_in == 1'b0) & (src_V_data_V_0_state == 2'd3) & (src_V_data_V_0_ack_out == 1'b1)))) begin
            src_V_data_V_0_state <= 2'd2;
        end else if ((((src_V_data_V_0_ack_out == 1'b0) & (src_V_data_V_0_state == 2'd1)) | ((src_V_data_V_0_ack_out == 1'b0) & (src_V_data_V_0_state == 2'd3) & (src_V_data_V_0_vld_in == 1'b1)))) begin
            src_V_data_V_0_state <= 2'd1;
        end else if (((~((src_V_data_V_0_vld_in == 1'b0) & (src_V_data_V_0_ack_out == 1'b1)) & ~((src_V_data_V_0_ack_out == 1'b0) & (src_V_data_V_0_vld_in == 1'b1)) & (src_V_data_V_0_state == 2'd3)) | ((src_V_data_V_0_state == 2'd1) & (src_V_data_V_0_ack_out == 1'b1)) | ((src_V_data_V_0_state == 2'd2) & (src_V_data_V_0_vld_in == 1'b1)))) begin
            src_V_data_V_0_state <= 2'd3;
        end else begin
            src_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_dest_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_V_dest_V_0_ack_out == 1'b1) & (src_V_dest_V_0_vld_out == 1'b1))) begin
            src_V_dest_V_0_sel_rd <= ~src_V_dest_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_dest_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_V_dest_V_0_ack_in == 1'b1) & (src_V_dest_V_0_vld_in == 1'b1))) begin
            src_V_dest_V_0_sel_wr <= ~src_V_dest_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((src_V_dest_V_0_state == 2'd2) & (src_V_dest_V_0_vld_in == 1'b0)) | ((src_V_dest_V_0_state == 2'd3) & (src_V_dest_V_0_vld_in == 1'b0) & (src_V_dest_V_0_ack_out == 1'b1)))) begin
            src_V_dest_V_0_state <= 2'd2;
        end else if ((((src_V_dest_V_0_state == 2'd1) & (src_V_dest_V_0_ack_out == 1'b0)) | ((src_V_dest_V_0_state == 2'd3) & (src_V_dest_V_0_ack_out == 1'b0) & (src_V_dest_V_0_vld_in == 1'b1)))) begin
            src_V_dest_V_0_state <= 2'd1;
        end else if (((~((src_V_dest_V_0_vld_in == 1'b0) & (src_V_dest_V_0_ack_out == 1'b1)) & ~((src_V_dest_V_0_ack_out == 1'b0) & (src_V_dest_V_0_vld_in == 1'b1)) & (src_V_dest_V_0_state == 2'd3)) | ((src_V_dest_V_0_state == 2'd1) & (src_V_dest_V_0_ack_out == 1'b1)) | ((src_V_dest_V_0_state == 2'd2) & (src_V_dest_V_0_vld_in == 1'b1)))) begin
            src_V_dest_V_0_state <= 2'd3;
        end else begin
            src_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_id_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_V_id_V_0_ack_out == 1'b1) & (src_V_id_V_0_vld_out == 1'b1))) begin
            src_V_id_V_0_sel_rd <= ~src_V_id_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_id_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_V_id_V_0_ack_in == 1'b1) & (src_V_id_V_0_vld_in == 1'b1))) begin
            src_V_id_V_0_sel_wr <= ~src_V_id_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_id_V_0_state <= 2'd0;
    end else begin
        if ((((src_V_id_V_0_state == 2'd2) & (src_V_id_V_0_vld_in == 1'b0)) | ((src_V_id_V_0_state == 2'd3) & (src_V_id_V_0_vld_in == 1'b0) & (src_V_id_V_0_ack_out == 1'b1)))) begin
            src_V_id_V_0_state <= 2'd2;
        end else if ((((src_V_id_V_0_state == 2'd1) & (src_V_id_V_0_ack_out == 1'b0)) | ((src_V_id_V_0_state == 2'd3) & (src_V_id_V_0_ack_out == 1'b0) & (src_V_id_V_0_vld_in == 1'b1)))) begin
            src_V_id_V_0_state <= 2'd1;
        end else if (((~((src_V_id_V_0_vld_in == 1'b0) & (src_V_id_V_0_ack_out == 1'b1)) & ~((src_V_id_V_0_ack_out == 1'b0) & (src_V_id_V_0_vld_in == 1'b1)) & (src_V_id_V_0_state == 2'd3)) | ((src_V_id_V_0_state == 2'd1) & (src_V_id_V_0_ack_out == 1'b1)) | ((src_V_id_V_0_state == 2'd2) & (src_V_id_V_0_vld_in == 1'b1)))) begin
            src_V_id_V_0_state <= 2'd3;
        end else begin
            src_V_id_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_keep_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_V_keep_V_0_ack_out == 1'b1) & (src_V_keep_V_0_vld_out == 1'b1))) begin
            src_V_keep_V_0_sel_rd <= ~src_V_keep_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_keep_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_V_keep_V_0_ack_in == 1'b1) & (src_V_keep_V_0_vld_in == 1'b1))) begin
            src_V_keep_V_0_sel_wr <= ~src_V_keep_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_keep_V_0_state <= 2'd0;
    end else begin
        if ((((src_V_keep_V_0_state == 2'd3) & (src_V_keep_V_0_vld_in == 1'b0) & (src_V_keep_V_0_ack_out == 1'b1)) | ((src_V_keep_V_0_state == 2'd2) & (src_V_keep_V_0_vld_in == 1'b0)))) begin
            src_V_keep_V_0_state <= 2'd2;
        end else if ((((src_V_keep_V_0_state == 2'd1) & (src_V_keep_V_0_ack_out == 1'b0)) | ((src_V_keep_V_0_state == 2'd3) & (src_V_keep_V_0_ack_out == 1'b0) & (src_V_keep_V_0_vld_in == 1'b1)))) begin
            src_V_keep_V_0_state <= 2'd1;
        end else if ((((src_V_keep_V_0_state == 2'd1) & (src_V_keep_V_0_ack_out == 1'b1)) | ((src_V_keep_V_0_state == 2'd2) & (src_V_keep_V_0_vld_in == 1'b1)) | (~((src_V_keep_V_0_vld_in == 1'b0) & (src_V_keep_V_0_ack_out == 1'b1)) & ~((src_V_keep_V_0_ack_out == 1'b0) & (src_V_keep_V_0_vld_in == 1'b1)) & (src_V_keep_V_0_state == 2'd3)))) begin
            src_V_keep_V_0_state <= 2'd3;
        end else begin
            src_V_keep_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_last_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_V_last_V_0_ack_out == 1'b1) & (src_V_last_V_0_vld_out == 1'b1))) begin
            src_V_last_V_0_sel_rd <= ~src_V_last_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_last_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_V_last_V_0_ack_in == 1'b1) & (src_V_last_V_0_vld_in == 1'b1))) begin
            src_V_last_V_0_sel_wr <= ~src_V_last_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((src_V_last_V_0_state == 2'd2) & (src_V_last_V_0_vld_in == 1'b0)) | ((src_V_last_V_0_state == 2'd3) & (src_V_last_V_0_vld_in == 1'b0) & (src_V_last_V_0_ack_out == 1'b1)))) begin
            src_V_last_V_0_state <= 2'd2;
        end else if ((((src_V_last_V_0_state == 2'd1) & (src_V_last_V_0_ack_out == 1'b0)) | ((src_V_last_V_0_state == 2'd3) & (src_V_last_V_0_ack_out == 1'b0) & (src_V_last_V_0_vld_in == 1'b1)))) begin
            src_V_last_V_0_state <= 2'd1;
        end else if (((~((src_V_last_V_0_vld_in == 1'b0) & (src_V_last_V_0_ack_out == 1'b1)) & ~((src_V_last_V_0_ack_out == 1'b0) & (src_V_last_V_0_vld_in == 1'b1)) & (src_V_last_V_0_state == 2'd3)) | ((src_V_last_V_0_state == 2'd1) & (src_V_last_V_0_ack_out == 1'b1)) | ((src_V_last_V_0_state == 2'd2) & (src_V_last_V_0_vld_in == 1'b1)))) begin
            src_V_last_V_0_state <= 2'd3;
        end else begin
            src_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_strb_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_V_strb_V_0_ack_out == 1'b1) & (src_V_strb_V_0_vld_out == 1'b1))) begin
            src_V_strb_V_0_sel_rd <= ~src_V_strb_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_strb_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_V_strb_V_0_ack_in == 1'b1) & (src_V_strb_V_0_vld_in == 1'b1))) begin
            src_V_strb_V_0_sel_wr <= ~src_V_strb_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_strb_V_0_state <= 2'd0;
    end else begin
        if ((((src_V_strb_V_0_state == 2'd2) & (src_V_strb_V_0_vld_in == 1'b0)) | ((src_V_strb_V_0_state == 2'd3) & (src_V_strb_V_0_vld_in == 1'b0) & (src_V_strb_V_0_ack_out == 1'b1)))) begin
            src_V_strb_V_0_state <= 2'd2;
        end else if ((((src_V_strb_V_0_state == 2'd1) & (src_V_strb_V_0_ack_out == 1'b0)) | ((src_V_strb_V_0_state == 2'd3) & (src_V_strb_V_0_ack_out == 1'b0) & (src_V_strb_V_0_vld_in == 1'b1)))) begin
            src_V_strb_V_0_state <= 2'd1;
        end else if (((~((src_V_strb_V_0_vld_in == 1'b0) & (src_V_strb_V_0_ack_out == 1'b1)) & ~((src_V_strb_V_0_ack_out == 1'b0) & (src_V_strb_V_0_vld_in == 1'b1)) & (src_V_strb_V_0_state == 2'd3)) | ((src_V_strb_V_0_state == 2'd1) & (src_V_strb_V_0_ack_out == 1'b1)) | ((src_V_strb_V_0_state == 2'd2) & (src_V_strb_V_0_vld_in == 1'b1)))) begin
            src_V_strb_V_0_state <= 2'd3;
        end else begin
            src_V_strb_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_user_V_0_sel_rd <= 1'b0;
    end else begin
        if (((src_V_user_V_0_ack_out == 1'b1) & (src_V_user_V_0_vld_out == 1'b1))) begin
            src_V_user_V_0_sel_rd <= ~src_V_user_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_user_V_0_sel_wr <= 1'b0;
    end else begin
        if (((src_V_user_V_0_ack_in == 1'b1) & (src_V_user_V_0_vld_in == 1'b1))) begin
            src_V_user_V_0_sel_wr <= ~src_V_user_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        src_V_user_V_0_state <= 2'd0;
    end else begin
        if ((((src_V_user_V_0_state == 2'd2) & (src_V_user_V_0_vld_in == 1'b0)) | ((src_V_user_V_0_state == 2'd3) & (src_V_user_V_0_vld_in == 1'b0) & (src_V_user_V_0_ack_out == 1'b1)))) begin
            src_V_user_V_0_state <= 2'd2;
        end else if ((((src_V_user_V_0_state == 2'd1) & (src_V_user_V_0_ack_out == 1'b0)) | ((src_V_user_V_0_state == 2'd3) & (src_V_user_V_0_ack_out == 1'b0) & (src_V_user_V_0_vld_in == 1'b1)))) begin
            src_V_user_V_0_state <= 2'd1;
        end else if (((~((src_V_user_V_0_vld_in == 1'b0) & (src_V_user_V_0_ack_out == 1'b1)) & ~((src_V_user_V_0_ack_out == 1'b0) & (src_V_user_V_0_vld_in == 1'b1)) & (src_V_user_V_0_state == 2'd3)) | ((src_V_user_V_0_state == 2'd1) & (src_V_user_V_0_ack_out == 1'b1)) | ((src_V_user_V_0_state == 2'd2) & (src_V_user_V_0_vld_in == 1'b1)))) begin
            src_V_user_V_0_state <= 2'd3;
        end else begin
            src_V_user_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_924)) begin
        if ((tmp_last_V_fu_144_p1 == 1'd1)) begin
            x <= 16'd0;
        end else if ((tmp_last_V_fu_144_p1 == 1'd0)) begin
            x <= tmp_5_fu_205_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_data_V_1_load_A == 1'b1)) begin
        dst_V_data_V_1_payload_A <= tmp_data_V_fu_196_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_data_V_1_load_B == 1'b1)) begin
        dst_V_data_V_1_payload_B <= tmp_data_V_fu_196_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_dest_V_1_load_A == 1'b1)) begin
        dst_V_dest_V_1_payload_A <= src_V_dest_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_dest_V_1_load_B == 1'b1)) begin
        dst_V_dest_V_1_payload_B <= src_V_dest_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_id_V_1_load_A == 1'b1)) begin
        dst_V_id_V_1_payload_A <= src_V_id_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_id_V_1_load_B == 1'b1)) begin
        dst_V_id_V_1_payload_B <= src_V_id_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_keep_V_1_load_A == 1'b1)) begin
        dst_V_keep_V_1_payload_A <= src_V_keep_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_keep_V_1_load_B == 1'b1)) begin
        dst_V_keep_V_1_payload_B <= src_V_keep_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_last_V_1_load_A == 1'b1)) begin
        dst_V_last_V_1_payload_A <= src_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_last_V_1_load_B == 1'b1)) begin
        dst_V_last_V_1_payload_B <= src_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_strb_V_1_load_A == 1'b1)) begin
        dst_V_strb_V_1_payload_A <= src_V_strb_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_strb_V_1_load_B == 1'b1)) begin
        dst_V_strb_V_1_payload_B <= src_V_strb_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_user_V_1_load_A == 1'b1)) begin
        dst_V_user_V_1_payload_A <= src_V_user_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((dst_V_user_V_1_load_B == 1'b1)) begin
        dst_V_user_V_1_payload_B <= src_V_user_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mask_read_reg_239 <= mask;
        tmp_last_V_reg_259 <= src_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_data_V_0_load_A == 1'b1)) begin
        src_V_data_V_0_payload_A <= src_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_data_V_0_load_B == 1'b1)) begin
        src_V_data_V_0_payload_B <= src_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_dest_V_0_load_A == 1'b1)) begin
        src_V_dest_V_0_payload_A <= src_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_dest_V_0_load_B == 1'b1)) begin
        src_V_dest_V_0_payload_B <= src_TDEST;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_id_V_0_load_A == 1'b1)) begin
        src_V_id_V_0_payload_A <= src_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_id_V_0_load_B == 1'b1)) begin
        src_V_id_V_0_payload_B <= src_TID;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_keep_V_0_load_A == 1'b1)) begin
        src_V_keep_V_0_payload_A <= src_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_keep_V_0_load_B == 1'b1)) begin
        src_V_keep_V_0_payload_B <= src_TKEEP;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_last_V_0_load_A == 1'b1)) begin
        src_V_last_V_0_payload_A <= src_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_last_V_0_load_B == 1'b1)) begin
        src_V_last_V_0_payload_B <= src_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_strb_V_0_load_A == 1'b1)) begin
        src_V_strb_V_0_payload_A <= src_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_strb_V_0_load_B == 1'b1)) begin
        src_V_strb_V_0_payload_B <= src_TSTRB;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_user_V_0_load_A == 1'b1)) begin
        src_V_user_V_0_payload_A <= src_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((src_V_user_V_0_load_B == 1'b1)) begin
        src_V_user_V_0_payload_B <= src_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_last_V_reg_259 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        y <= tmp_4_fu_227_p2;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        dst_TDATA_blk_n = dst_V_data_V_1_state[1'd1];
    end else begin
        dst_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((dst_V_data_V_1_sel == 1'b1)) begin
        dst_V_data_V_1_data_out = dst_V_data_V_1_payload_B;
    end else begin
        dst_V_data_V_1_data_out = dst_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_V_data_V_1_vld_in = 1'b1;
    end else begin
        dst_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((dst_V_dest_V_1_sel == 1'b1)) begin
        dst_V_dest_V_1_data_out = dst_V_dest_V_1_payload_B;
    end else begin
        dst_V_dest_V_1_data_out = dst_V_dest_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_V_dest_V_1_vld_in = 1'b1;
    end else begin
        dst_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((dst_V_id_V_1_sel == 1'b1)) begin
        dst_V_id_V_1_data_out = dst_V_id_V_1_payload_B;
    end else begin
        dst_V_id_V_1_data_out = dst_V_id_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_V_id_V_1_vld_in = 1'b1;
    end else begin
        dst_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((dst_V_keep_V_1_sel == 1'b1)) begin
        dst_V_keep_V_1_data_out = dst_V_keep_V_1_payload_B;
    end else begin
        dst_V_keep_V_1_data_out = dst_V_keep_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_V_keep_V_1_vld_in = 1'b1;
    end else begin
        dst_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((dst_V_last_V_1_sel == 1'b1)) begin
        dst_V_last_V_1_data_out = dst_V_last_V_1_payload_B;
    end else begin
        dst_V_last_V_1_data_out = dst_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_V_last_V_1_vld_in = 1'b1;
    end else begin
        dst_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((dst_V_strb_V_1_sel == 1'b1)) begin
        dst_V_strb_V_1_data_out = dst_V_strb_V_1_payload_B;
    end else begin
        dst_V_strb_V_1_data_out = dst_V_strb_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_V_strb_V_1_vld_in = 1'b1;
    end else begin
        dst_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((dst_V_user_V_1_sel == 1'b1)) begin
        dst_V_user_V_1_data_out = dst_V_user_V_1_payload_B;
    end else begin
        dst_V_user_V_1_data_out = dst_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dst_V_user_V_1_vld_in = 1'b1;
    end else begin
        dst_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_TDATA_blk_n = src_V_data_V_0_state[1'd0];
    end else begin
        src_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_V_data_V_0_ack_out = 1'b1;
    end else begin
        src_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_V_data_V_0_sel == 1'b1)) begin
        src_V_data_V_0_data_out = src_V_data_V_0_payload_B;
    end else begin
        src_V_data_V_0_data_out = src_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_V_dest_V_0_ack_out = 1'b1;
    end else begin
        src_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_V_dest_V_0_sel == 1'b1)) begin
        src_V_dest_V_0_data_out = src_V_dest_V_0_payload_B;
    end else begin
        src_V_dest_V_0_data_out = src_V_dest_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_V_id_V_0_ack_out = 1'b1;
    end else begin
        src_V_id_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_V_id_V_0_sel == 1'b1)) begin
        src_V_id_V_0_data_out = src_V_id_V_0_payload_B;
    end else begin
        src_V_id_V_0_data_out = src_V_id_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_V_keep_V_0_ack_out = 1'b1;
    end else begin
        src_V_keep_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_V_keep_V_0_sel == 1'b1)) begin
        src_V_keep_V_0_data_out = src_V_keep_V_0_payload_B;
    end else begin
        src_V_keep_V_0_data_out = src_V_keep_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_V_last_V_0_ack_out = 1'b1;
    end else begin
        src_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_V_last_V_0_sel == 1'b1)) begin
        src_V_last_V_0_data_out = src_V_last_V_0_payload_B;
    end else begin
        src_V_last_V_0_data_out = src_V_last_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_V_strb_V_0_ack_out = 1'b1;
    end else begin
        src_V_strb_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_V_strb_V_0_sel == 1'b1)) begin
        src_V_strb_V_0_data_out = src_V_strb_V_0_payload_B;
    end else begin
        src_V_strb_V_0_data_out = src_V_strb_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_V_user_V_0_ack_out = 1'b1;
    end else begin
        src_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((src_V_user_V_0_sel == 1'b1)) begin
        src_V_user_V_0_data_out = src_V_user_V_0_payload_B;
    end else begin
        src_V_user_V_0_data_out = src_V_user_V_0_payload_A;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((dst_V_dest_V_1_ack_in == 1'b0) | (dst_V_id_V_1_ack_in == 1'b0) | (dst_V_last_V_1_ack_in == 1'b0) | (dst_V_user_V_1_ack_in == 1'b0) | (dst_V_strb_V_1_ack_in == 1'b0) | (dst_V_keep_V_1_ack_in == 1'b0) | (dst_V_data_V_1_ack_in == 1'b0))) | ((src_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((dst_V_dest_V_1_ack_in == 1'b0) | (dst_V_id_V_1_ack_in == 1'b0) | (dst_V_last_V_1_ack_in == 1'b0) | (dst_V_user_V_1_ack_in == 1'b0) | (dst_V_strb_V_1_ack_in == 1'b0) | (dst_V_keep_V_1_ack_in == 1'b0) | (dst_V_data_V_1_ack_in == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((dst_V_data_V_1_ack_in == 1'b0) | (src_V_data_V_0_vld_out == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((dst_V_dest_V_1_ack_in == 1'b0) | (dst_V_id_V_1_ack_in == 1'b0) | (dst_V_last_V_1_ack_in == 1'b0) | (dst_V_user_V_1_ack_in == 1'b0) | (dst_V_strb_V_1_ack_in == 1'b0) | (dst_V_keep_V_1_ack_in == 1'b0) | (dst_V_data_V_1_ack_in == 1'b0))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((dst_V_data_V_1_ack_in == 1'b0) | (src_V_data_V_0_vld_out == 1'b0))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (src_V_data_V_0_vld_out == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((dst_V_dest_V_1_ack_in == 1'b0) | (dst_V_id_V_1_ack_in == 1'b0) | (dst_V_last_V_1_ack_in == 1'b0) | (dst_V_user_V_1_ack_in == 1'b0) | (dst_V_strb_V_1_ack_in == 1'b0) | (dst_V_keep_V_1_ack_in == 1'b0) | (dst_V_data_V_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_condition_924 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign brmerge_fu_178_p2 = (p_not1_fu_172_p2 | invert_fu_162_p2);

assign dst_TDATA = dst_V_data_V_1_data_out;

assign dst_TDEST = dst_V_dest_V_1_data_out;

assign dst_TID = dst_V_id_V_1_data_out;

assign dst_TKEEP = dst_V_keep_V_1_data_out;

assign dst_TLAST = dst_V_last_V_1_data_out;

assign dst_TSTRB = dst_V_strb_V_1_data_out;

assign dst_TUSER = dst_V_user_V_1_data_out;

assign dst_TVALID = dst_V_dest_V_1_state[1'd0];

assign dst_V_data_V_1_ack_in = dst_V_data_V_1_state[1'd1];

assign dst_V_data_V_1_ack_out = dst_TREADY;

assign dst_V_data_V_1_load_A = (~dst_V_data_V_1_sel_wr & dst_V_data_V_1_state_cmp_full);

assign dst_V_data_V_1_load_B = (dst_V_data_V_1_state_cmp_full & dst_V_data_V_1_sel_wr);

assign dst_V_data_V_1_sel = dst_V_data_V_1_sel_rd;

assign dst_V_data_V_1_state_cmp_full = ((dst_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_V_data_V_1_vld_out = dst_V_data_V_1_state[1'd0];

assign dst_V_dest_V_1_ack_in = dst_V_dest_V_1_state[1'd1];

assign dst_V_dest_V_1_ack_out = dst_TREADY;

assign dst_V_dest_V_1_load_A = (~dst_V_dest_V_1_sel_wr & dst_V_dest_V_1_state_cmp_full);

assign dst_V_dest_V_1_load_B = (dst_V_dest_V_1_state_cmp_full & dst_V_dest_V_1_sel_wr);

assign dst_V_dest_V_1_sel = dst_V_dest_V_1_sel_rd;

assign dst_V_dest_V_1_state_cmp_full = ((dst_V_dest_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_V_dest_V_1_vld_out = dst_V_dest_V_1_state[1'd0];

assign dst_V_id_V_1_ack_in = dst_V_id_V_1_state[1'd1];

assign dst_V_id_V_1_ack_out = dst_TREADY;

assign dst_V_id_V_1_load_A = (~dst_V_id_V_1_sel_wr & dst_V_id_V_1_state_cmp_full);

assign dst_V_id_V_1_load_B = (dst_V_id_V_1_state_cmp_full & dst_V_id_V_1_sel_wr);

assign dst_V_id_V_1_sel = dst_V_id_V_1_sel_rd;

assign dst_V_id_V_1_state_cmp_full = ((dst_V_id_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_V_id_V_1_vld_out = dst_V_id_V_1_state[1'd0];

assign dst_V_keep_V_1_ack_in = dst_V_keep_V_1_state[1'd1];

assign dst_V_keep_V_1_ack_out = dst_TREADY;

assign dst_V_keep_V_1_load_A = (~dst_V_keep_V_1_sel_wr & dst_V_keep_V_1_state_cmp_full);

assign dst_V_keep_V_1_load_B = (dst_V_keep_V_1_state_cmp_full & dst_V_keep_V_1_sel_wr);

assign dst_V_keep_V_1_sel = dst_V_keep_V_1_sel_rd;

assign dst_V_keep_V_1_state_cmp_full = ((dst_V_keep_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_V_keep_V_1_vld_out = dst_V_keep_V_1_state[1'd0];

assign dst_V_last_V_1_ack_in = dst_V_last_V_1_state[1'd1];

assign dst_V_last_V_1_ack_out = dst_TREADY;

assign dst_V_last_V_1_load_A = (~dst_V_last_V_1_sel_wr & dst_V_last_V_1_state_cmp_full);

assign dst_V_last_V_1_load_B = (dst_V_last_V_1_state_cmp_full & dst_V_last_V_1_sel_wr);

assign dst_V_last_V_1_sel = dst_V_last_V_1_sel_rd;

assign dst_V_last_V_1_state_cmp_full = ((dst_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_V_last_V_1_vld_out = dst_V_last_V_1_state[1'd0];

assign dst_V_strb_V_1_ack_in = dst_V_strb_V_1_state[1'd1];

assign dst_V_strb_V_1_ack_out = dst_TREADY;

assign dst_V_strb_V_1_load_A = (~dst_V_strb_V_1_sel_wr & dst_V_strb_V_1_state_cmp_full);

assign dst_V_strb_V_1_load_B = (dst_V_strb_V_1_state_cmp_full & dst_V_strb_V_1_sel_wr);

assign dst_V_strb_V_1_sel = dst_V_strb_V_1_sel_rd;

assign dst_V_strb_V_1_state_cmp_full = ((dst_V_strb_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_V_strb_V_1_vld_out = dst_V_strb_V_1_state[1'd0];

assign dst_V_user_V_1_ack_in = dst_V_user_V_1_state[1'd1];

assign dst_V_user_V_1_ack_out = dst_TREADY;

assign dst_V_user_V_1_load_A = (~dst_V_user_V_1_sel_wr & dst_V_user_V_1_state_cmp_full);

assign dst_V_user_V_1_load_B = (dst_V_user_V_1_state_cmp_full & dst_V_user_V_1_sel_wr);

assign dst_V_user_V_1_sel = dst_V_user_V_1_sel_rd;

assign dst_V_user_V_1_state_cmp_full = ((dst_V_user_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign dst_V_user_V_1_vld_out = dst_V_user_V_1_state[1'd0];

assign invert_fu_162_p2 = (tmp_fu_159_p1 ^ 1'd1);

assign p_not1_fu_172_p2 = ((x < 16'd691) ? 1'b1 : 1'b0);

assign p_not_fu_184_p2 = (src_V_data_V_0_data_out | 32'd4278190080);

assign p_s_fu_190_p2 = (p_not_fu_184_p2 ^ 32'd16777215);

assign src_TREADY = src_V_dest_V_0_state[1'd1];

assign src_V_data_V_0_ack_in = src_V_data_V_0_state[1'd1];

assign src_V_data_V_0_load_A = (src_V_data_V_0_state_cmp_full & ~src_V_data_V_0_sel_wr);

assign src_V_data_V_0_load_B = (src_V_data_V_0_state_cmp_full & src_V_data_V_0_sel_wr);

assign src_V_data_V_0_sel = src_V_data_V_0_sel_rd;

assign src_V_data_V_0_state_cmp_full = ((src_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_V_data_V_0_vld_in = src_TVALID;

assign src_V_data_V_0_vld_out = src_V_data_V_0_state[1'd0];

assign src_V_dest_V_0_ack_in = src_V_dest_V_0_state[1'd1];

assign src_V_dest_V_0_load_A = (src_V_dest_V_0_state_cmp_full & ~src_V_dest_V_0_sel_wr);

assign src_V_dest_V_0_load_B = (src_V_dest_V_0_state_cmp_full & src_V_dest_V_0_sel_wr);

assign src_V_dest_V_0_sel = src_V_dest_V_0_sel_rd;

assign src_V_dest_V_0_state_cmp_full = ((src_V_dest_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_V_dest_V_0_vld_in = src_TVALID;

assign src_V_dest_V_0_vld_out = src_V_dest_V_0_state[1'd0];

assign src_V_id_V_0_ack_in = src_V_id_V_0_state[1'd1];

assign src_V_id_V_0_load_A = (src_V_id_V_0_state_cmp_full & ~src_V_id_V_0_sel_wr);

assign src_V_id_V_0_load_B = (src_V_id_V_0_state_cmp_full & src_V_id_V_0_sel_wr);

assign src_V_id_V_0_sel = src_V_id_V_0_sel_rd;

assign src_V_id_V_0_state_cmp_full = ((src_V_id_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_V_id_V_0_vld_in = src_TVALID;

assign src_V_id_V_0_vld_out = src_V_id_V_0_state[1'd0];

assign src_V_keep_V_0_ack_in = src_V_keep_V_0_state[1'd1];

assign src_V_keep_V_0_load_A = (src_V_keep_V_0_state_cmp_full & ~src_V_keep_V_0_sel_wr);

assign src_V_keep_V_0_load_B = (src_V_keep_V_0_state_cmp_full & src_V_keep_V_0_sel_wr);

assign src_V_keep_V_0_sel = src_V_keep_V_0_sel_rd;

assign src_V_keep_V_0_state_cmp_full = ((src_V_keep_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_V_keep_V_0_vld_in = src_TVALID;

assign src_V_keep_V_0_vld_out = src_V_keep_V_0_state[1'd0];

assign src_V_last_V_0_ack_in = src_V_last_V_0_state[1'd1];

assign src_V_last_V_0_load_A = (src_V_last_V_0_state_cmp_full & ~src_V_last_V_0_sel_wr);

assign src_V_last_V_0_load_B = (src_V_last_V_0_state_cmp_full & src_V_last_V_0_sel_wr);

assign src_V_last_V_0_sel = src_V_last_V_0_sel_rd;

assign src_V_last_V_0_state_cmp_full = ((src_V_last_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_V_last_V_0_vld_in = src_TVALID;

assign src_V_last_V_0_vld_out = src_V_last_V_0_state[1'd0];

assign src_V_strb_V_0_ack_in = src_V_strb_V_0_state[1'd1];

assign src_V_strb_V_0_load_A = (src_V_strb_V_0_state_cmp_full & ~src_V_strb_V_0_sel_wr);

assign src_V_strb_V_0_load_B = (src_V_strb_V_0_state_cmp_full & src_V_strb_V_0_sel_wr);

assign src_V_strb_V_0_sel = src_V_strb_V_0_sel_rd;

assign src_V_strb_V_0_state_cmp_full = ((src_V_strb_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_V_strb_V_0_vld_in = src_TVALID;

assign src_V_strb_V_0_vld_out = src_V_strb_V_0_state[1'd0];

assign src_V_user_V_0_ack_in = src_V_user_V_0_state[1'd1];

assign src_V_user_V_0_load_A = (src_V_user_V_0_state_cmp_full & ~src_V_user_V_0_sel_wr);

assign src_V_user_V_0_load_B = (src_V_user_V_0_state_cmp_full & src_V_user_V_0_sel_wr);

assign src_V_user_V_0_sel = src_V_user_V_0_sel_rd;

assign src_V_user_V_0_state_cmp_full = ((src_V_user_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign src_V_user_V_0_vld_in = src_TVALID;

assign src_V_user_V_0_vld_out = src_V_user_V_0_state[1'd0];

assign tmp_4_fu_227_p2 = (y + 16'd1);

assign tmp_5_fu_205_p2 = (x + 16'd1);

assign tmp_data_V_fu_196_p3 = ((brmerge_fu_178_p2[0:0] === 1'b1) ? src_V_data_V_0_data_out : p_s_fu_190_p2);

assign tmp_fu_159_p1 = mask_read_reg_239[0:0];

assign tmp_last_V_fu_144_p1 = src_V_last_V_0_data_out;

endmodule //stream
