

close all;
clear variables;

filename = 'hammingcoefficients_tukey.h';
fID = fopen(filename, 'w+');

fprintf(fID,...
'/// Generated by MATLAB\n// do more stuff\n\n');

hamm = sqrt(tukeywin(80) * tukeywin(45)');

fprintf(fID, 'u16 hamming[%d][%d] = {\n', size(hamm,1),size(hamm,2));
for i = 1:80
    for j = 1:45
        fprintf(fID, '%d, ', uint16(round(hamm(i,j) * pow2(16))));
    end
    fprintf(fID, '\n'); 
end

fprintf(fID, '};');

res = fclose(fID)
