// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xstream.h"

extern XStream_Config XStream_ConfigTable[];

XStream_Config *XStream_LookupConfig(u16 DeviceId) {
	XStream_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSTREAM_NUM_INSTANCES; Index++) {
		if (XStream_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XStream_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XStream_Initialize(XStream *InstancePtr, u16 DeviceId) {
	XStream_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XStream_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XStream_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

